ipfs-cluster/ipfs-cluster

architecture.md
cluster.go
ipfs-cluster-ctl/main.go
ipfs-cluster-service/main.go

Noticed this, and this was slightly bugging me.
Skimmed through all strings, and didn't find any other obvious errors.

Fix typo and remove trailing whitespace.

---

cluster.go
cluster_test.go
consensus.go
consensus_test.go

Fix #25: Only the consensus layer should deal with leaders

---

Makefile
README.md
cluster.go
cluster_test.go
consensus.go
ipfs-cluster-ctl/Makefile
ipfs-cluster-ctl/main.go
ipfs-cluster-service/Makefile
ipfs-cluster-service/main.go
ipfscluster.go
package.json
rest_api.go
rest_api_test.go
rpc_api.go
rpc_api_test.go
version.go

Fixes #21 
* Use urfave/cli which handles nicer formatting and help in commands
* Add an /ID endpoint to cluster and support from it

ipfs-cluster-ctl improvements

---

.gitignore
Makefile
architecture.md
cluster.go
cluster_test.go
consensus.go
ipfs_http_connector.go
ipfscluster.go
map_pin_tracker.go
package.json
raft.go
rest_api.go
rpc_api.go
rpc_api_test.go

Fixes #20 and has involved a bunch of work gx-ing trees

Dependency management: gx all deps + fetch gx from dist.ifps.io

---

CAPTAIN.LOG.md
README.md
allocator/numpinalloc/numpinalloc.go
api/types_test.go
architecture.md
cluster.go
informer/numpin/numpin.go
ipfscluster.go
ipfscluster_test.go
peer_monitor.go
rpc_api.go
state/mapstate/map_state.go
test/cids.go
test/ipfs_mock.go
test/rpc_api_mock.go

Documentation/golint/govet stuff. Checking tests pass.

Cleanup and docs

---

consensus.go
ipfs_http_connector.go
rest_api.go

Cleaning up some ugly code
License: MIT

Unify the way of handling contex and cancels in components.

---

Dockerfile
docker/entrypoint.sh

@lgierth @Kubuxu would appreciate if you have a look to this and tell me if I'm doing something wrong, since I'm not much into docker. I have copied from ipfs as much as I could... (and works for me)

Add Dockerfile

---

Dockerfile
api/types.go
api/types_test.go
cluster.go
cluster_test.go
consensus.go
consensus_test.go
docker/entrypoint.sh
ipfs-cluster-ctl/formatters.go
ipfs-cluster-ctl/main.go
ipfs_http_connector.go
ipfscluster.go
ipfscluster_test.go
log_op.go
log_op_test.go
map_pin_tracker.go
peer_manager_test.go
rest_api.go
rest_api_test.go
rpc_api.go
state/mapstate/map_state.go
state/mapstate/map_state_test.go
test/ipfs_mock.go
test/rpc_api_mock.go

This allows to manually set the replication factor per-pin, while using the configuration value otherwise.

Allow specifying a replication factor per pin

---

cluster.go
ipfscluster_test.go

There was a bug in the test for re-allocation which hid another
bug in the re-allocation process where a pin which needs to be
re-allocated would only be assigned to the new destinations and not
anymore to the valid allocations it had previously
License: MIT

Fix pin re-allocation when it's already pinned

---

api/restapi/restapi.go
cluster_test.go
ipfsconn/ipfshttp/ipfshttp.go
ipfsconn/ipfshttp/ipfshttp_test.go
pintracker/maptracker/maptracker_test.go

Take advantage of go-multiaddr-net utilities.

---

ipfsconn/ipfshttp/ipfshttp.go
ipfsconn/ipfshttp/ipfshttp_test.go

Added extra test for it.
License: MIT

Fix ipfs proxy not respecting return status codes

---

api/restapi/restapi.go
api/restapi/restapi_test.go
api/types.go
cluster.go
config.go
config_test.go
ipfs-cluster-ctl/formatters.go
ipfs-cluster-ctl/main.go
ipfs-cluster-service/main.go

Fixes #77 
Fixes #76 
Fixes #75 
and does not bootstrap twice.

Some small fixes

---

cluster.go
ipfs-cluster-service/Makefile
ipfsconn/ipfshttp/ipfshttp.go
ipfsconn/ipfshttp/ipfshttp_test.go
test/ipfs_mock.go

Should work, but will re-look again. I'm tired and there are many small things to take care of.

Fix #57: Hijack /add requests and pin items in cluster

---

ipfs-cluster-service/main.go

Catch SIGHUP too

---

config.go

Set default allocation strategy in default configuration

---

README.md
api/restapi/restapi.go
api/restapi/restapi_test.go
cluster.go
cluster_test.go
ipfs-cluster-ctl/main.go
ipfsconn/ipfshttp/ipfshttp.go
ipfsconn/ipfshttp/ipfshttp_test.go
rpc_api.go
test/ipfs_mock.go
test/rpc_api_mock.go

I have updated API endpoints to be /allocations rather than /pinlinst
It's more self-explanatory.
#87 
License: MIT

Fix #87: Implement ipfs-cluster-ctl pin ls <cid>

---

README.md
docs/ipfs-cluster-guide.md

This should fix what I meant in #84
License: MIT

A guide to running ipfs cluster

---

cluster.go
ipfscluster_test.go

We were setting a nil Cid on the PinInfo object for errors.
Cleaned up the logic a bit, and added comments
License: MIT

Fix #105: Panic when calling globalPinInfoCid and peers are down

---

.travis.yml
Makefile
cluster.go
ipfscluster_test.go
monitor/basic/peer_monitor.go
sharness/lib/test-lib.sh
sharness/run-sharness-tests.sh
sharness/t0010-ctl-basic-commands.sh
sharness/t0020-service-basic-commands.sh
sharness/t0025-ctl-status-report-commands.sh
sharness/t0030-ctl-pin.sh

* Added travis sharness build
* ipfs-cluster-ctl help text width overflow fixed
* Expect success from fixed sharness test
* First travis-sharness PR touch up
Undoes gx rewrite of cluster-ctl dependencies
Undoess linebreaking of usage descriptions
Changes test to check for lines in excess of 120 chars instead of 80
run-sharness script now correctly tracks exit codes and exits with error
Comes from #110

Travis sharness

---

ipfs-cluster-ctl/formatters.go
ipfs-cluster-service/main.go
sharness/lib/test-lib.sh

A couple of changes after playing with cluster a little bit, before tagging a new release.

Release fixes

---

README.md

Point IRC badge to our own channel
Point to protocol.ai

Badges fixes

---

CAPTAIN.LOG.md
ROADMAP.md

Will let this sink for a few hours

Updated Captain's log and added Q3 Roadmap

---

ipfs-cluster-ctl/dist/README.md
ipfs-cluster-service/dist/README.md

Make sure dist READMEs are up to date

---

package.json

Fix #138: Update raft/raft-boltdb/boltdb

---

docker/cluster-restart.sh
docker/test-entrypoint.sh

One-line fix to make testing image compatible with cluster secret feature.  Addresses #150

set cluster secret to empty in test image

---

CHANGELOG.md

Add changelog for v0.2.0

---

cluster_config.go
cluster_config_test.go

Fix #208: Set replication factor from loaded json

---

cluster.go
config/config.go
ipfs-cluster-service/main.go
peer_manager.go

Issue #213: Fix save in cluster component config

---

README.md
docs/ipfs-cluster-guide.md

I have just pushed an initial version of ipfs-cluster to the snapcraft store:
https://discuss.ipfs.io/t/start-testing-the-ipfs-cluster-snap/1422

Add the instructions to install the snap

---

.travis.yml
snap/snap-in-docker.sh
snap/snap-multiarch.sh
snap/snapcraft.yaml

I tested this in my branch:
* amd64: https://travis-ci.org/elopio/ipfs-cluster/builds/302877222#L2028
* armhf: https://travis-ci.org/elopio/ipfs-cluster/builds/302877222#L2890
* arm64 https://travis-ci.org/elopio/ipfs-cluster/builds/302877222#L3757

Move the snap deploy script to a separate file

---

.codeclimate.yml
api/rest/client/request.go
api/types.go
api/types_test.go
cluster_config.go
ipfs-cluster-ctl/main.go
ipfs-cluster-service/main.go
ipfs-cluster-service/migrate.go
logging.go

I'm seeing some errors in real cluster with ipfs-cluster-ctl and I think they might be because of this...

Fix: client requests and multiaddresses parsing

---

.codeclimate.yml

Adjust some codeclimate settings

---

docs/ipfs-cluster-guide.md

Docs/guide: describe upgrade procedures in more detail

---

docs/dag-sharding-rfc.md

@hsanjuan, this is the beginning of the rough draft RFC I have been working on.  Consider it under heavy development this week.  The unfilled sections are coming soon, plus there is more I would like to add to the RAID 0 section.  
I decided to go with a document + PR review process rather than an issue so that I could add and version and receive comments with better UX.  I'm not necessarily trying to add this document to the repo.
Forgive the somewhat scattered nature of a few paragraphs, particularly the TODOs, I am at a point where I have a lot of questions and ideas and don't want to lose track of them.  Let me know if you don't know what I mean by something and I'll add clarity.
By the end of this I'm hoping for a reasonably clear path forward to implement these new features to …

ipfs-cluster dag/file sharding RFC WIP

---

.travis.yml
Makefile
ci/Jenkinsfile
cluster.go
config_test.go
consensus/raft/consensus_test.go
coverage.sh
ipfscluster_test.go
monitor/basic/peer_monitor.go
peer_manager_test.go

Adding Jenkinsfile -- Experiment

---

state/mapstate/map_state.go

It seems we have problems deserializing on top of an already
initialized state.
License: MIT

Fix #297: State unmarshal

---

api/rest/client/client_test.go
api/rest/restapi.go
api/rest/restapi_test.go
ci/Jenkinsfile
cluster.go
consensus/raft/consensus_test.go
consensus/raft/log_op_test.go
ipfscluster_test.go
ipfsconn/ipfshttp/ipfshttp.go
ipfsconn/ipfshttp/ipfshttp_test.go
peer_manager.go
peer_manager_test.go
rpc_api.go

I really want that jenkins works
License: MIT

Fix jenkins tests

---

api/rest/restapi_test.go
ipfs-cluster-ctl/graph_test.go

Fixing a few bugs causing issues in jenkins ci builds.

fix conn graph failures

---

api/rest/client/methods.go
api/rest/client/request.go
api/rest/restapi.go
ipfs-cluster-ctl/files.go
ipfs-cluster-ctl/main.go
package.json

* parse files from fs to cmdkit.File objects
* stream over rest client to ipfs-cluster-service handler

Stream HTTP requests carrying multi-part files over the REST API for adding files via ipfs-cluster-ctl add

---

.travis.yml

This should speed up builds a bit
License: MIT

Add cache configuration to .travis.yml

---

ipfs-cluster-service/main.go

Fix daemon error

---

cluster.go
ipfs-cluster-service/main.go

Since the commit variable is not set in these builds :(
License: MIT

Fix: official builds panic on start

---

docs/ipfs-cluster-guide.md

Link to "How to Build and Update a Cluster" was broken.
License: MIT
Signed-off-by: Adrian Lanzafame <adrian.lanzafame@protocol.ai>

Fix broken link

---

api/rest/client/client.go
ipfs-cluster-ctl/main.go

No logic behind how much I increased the value by. @hsanjuan suggestions welcome?
Resolves #323.

rest/client: double default timeout

---

cluster.go

This would look like:
```
[14:24:33] ~/clustertest $ ipfs-cluster-service -c c2 --bootstrap /ip4/127.0.0.1/tcp/10096/ipfs/Qma7KpVhrTgkdUxBanyVSffjydx9dceDXDz1K8GzspB7me
14:24:42.418  INFO    cluster: IPFS Cluster v0.3.4-de07a9dd listening on: cluster.go:95
14:24:42.419  INFO    cluster:         /ip4/127.0.0.1/tcp/9096/ipfs/Qmb9qpF5JkxkJWfmoXydwjATbhBwfp2uF8yVC8BbhyXpPd cluster.go:100
14:24:42.419  INFO    cluster:         /ip4/192.168.123.103/tcp/9096/ipfs/Qmb9qpF5JkxkJWfmoXydwjATbhBwfp2uF8yVC8BbhyXpPd cluster.go:100
14:24:42.422  INFO    cluster: Bootstrapping to /ip4/127.0.0.1/tcp/10096/ipfs/Qma7KpVhrTgkdUxBanyVSffjydx9dceDXDz1K8GzspB7me cluster.go:486
14:24:42.422  INFO    restapi: REST API: /ip4/127.0.0.1/tcp/9094 restapi.go:285
14:24:42.422  INFO   ipfshttp: IPFS Proxy: …
```

Improve errors for bootstraps

---

api/rest/config.go

Fix: downcase json keys for api config

---

cluster_test.go
test/cids.go

More tests to follow but ready for review

Tests of new pin types

---

api/rest/config.go
ipfsconn/ipfshttp/config.go
pstoremgr/pstoremgr.go

Running `make check` manually gives me some errors from govet. I'm not sure why travis doesn't see them, but this fixes them.

Fix: some govet warnings

---

ipfsconn/ipfshttp/config.go
pintracker/maptracker/config.go

Set refs as default pinning method, with 10 parallel pins

---

ipfsconn/ipfshttp/ipfshttp.go

so that the IPFSRequestTimeout is triggered on all other requests
other than those two. Timing out is handled by the context timeout
in the pin and unpin functions.
License: MIT

ipfshttp: Use custom http clients for pin/unpin

---

clusterhost.go
package.json

Fix #346: Enable NAT hole punching for libp2p host

---

package.json

Fix #433: Use new floodsub version

---

.github/ISSUE_TEMPLATE.md

Unfortunately, can't really test this until merged.
#412

Fix #412: Add an issue template

---

package.json

gx: update go-libp2p

---

ipfs-cluster-ctl/graph_test.go

Just ran
gofmt -w .
on the project root. That's all. Helps with legibility.

all: gofmt

---

.travis.yml

License: MIT
Signed-off-by: Lilith McMullen <iggnsthe@live.com>

Fix #465: Remove unneeded repotoken from goveralls

---

README.md

Readme: add link to user registry form

---

state/mapstate/map_state.go
state/mapstate/map_state_test.go
state/mapstate/migrate.go

This adds state migration to new state format version 5.
License: MIT

State migrations for sharding

---

ipfsconn/ipfshttp/ipfshttp.go
peer_manager_test.go
test/ipfs_mock.go

This will make them very fast.
Fixes #280
License: MIT

IPFSHttp: Add "size-only=true" flag to repo/stat calls

---

ipfsconn/ipfshttp/ipfshttp.go

Right now it only looks for recursive pins, but with sharding we will need to check direct pins too (and maybe others).

IPFSPinLsCid should try to find pins in the direct pinset too.

---

ipfsconn/ipfshttp/ipfshttp.go
state/mapstate/migrate.go

Fix PinLsCid and pins with maxdepth 0 after migration

---

adder/adder.go
adder/ipfsadd/add.go
api/add.go
ipfs-cluster-ctl/main.go
package.json
sharness/t0031-ctl-add.sh

Additionally, remove dependency to go-ipfs after extraction from
"go-mfs".
License: MIT

AddParams: support "cid-version" and "hash" function.

---

ipfs-cluster-ctl/formatters.go

Small adjustment to "pin ls" human output in ctl.

---

CHANGELOG.md

Changelog for v0.5.0

---

ipfs-cluster-ctl/graph.go
package.json

gx update go-dot

---

README.md

There was a slight grammar mistake. Now it is gone, and this sentence matches the one on our website.
I submitted this PR yesterday, but it wasn't signed properly. I'm opening a new PR to test where the signature should go in the GH web interface (clearly did not have it in the right place last time).
License: MIT
Signed-off-by: Michelle Hertzfeld mhertzfeld@gmail.com

Copyedit in README

---

.travis.yml

Fix #520 snapcraft stages

---

.travis.yml

Also, make sure they are only built on master builds of the original
repo.
License: MIT

Fix #544: Push Snaps to the right channel depending on tags

---

.travis.yml
Dockerfile
Dockerfile-test
package.json
snap/snapcraft.yaml

Update to go-1.11

---

.travis.yml
snap/snap-multiarch.sh
snap/snapcraft.yaml

Snap build fixes. Re-enable multiarch builds.

---

api/rest/client/methods.go

Docs: Fix comment for WaitFor function

---

ipfsconn/ipfshttp/ipfshttp.go

ipfshttp: remove custom proxy and use stdlib reverse proxy

---

adder/adder.go
adder/ipfsadd/add.go
api/rest/client/client.go
api/rest/client/methods.go
ipfsconn/ipfshttp/ipfshttp.go
package.json
test/sharding.go

Related: https://github.com/ipfs/go-ipfs-cmdkit/pull/31

Files package has been extracted from cmdkit

---

package.json

Upgrade to libp2p 6.0.23

---

api/rest/client/client_test.go
consensus/raft/consensus_test.go
ipfscluster_test.go
peer_manager_test.go

I merged too quickly what I thought was a harmless libp2p upgrade and this is the result.

Fix tests with latest libp2p

---

adder/ipfsadd/add.go
package.json

Upgrade ipld-related dependencies. Remove importers DAG forced-Batching.

---

monitor/pubsubmon/pubsubmon.go
monitor/pubsubmon/pubsubmon_test.go
package.json

Update to latest go-libp2p-pubsub (with renames)

---

pintracker/optracker/operationtracker.go
pintracker/pintracker_test.go

Fix #600: Remote pins should not error

---

ipfsconn/ipfshttp/ipfshttp.go

Fix the paths handled by the proxy

---

CHANGELOG.md

Changelog for v0.7.0

---

CHANGELOG.md
api/rest/client/methods_test.go
api/rest/restapi_test.go

Remove shard testing folders

---

package.json

Update to libp2p-6.0.29 (and general dep alignment)

---

api/rest/client/methods_test.go
api/rest/restapi_test.go
api/types.go
sharness/lib/test-lib.sh
sharness/t0025-ctl-status-report-commands.sh
sharness/t0032-ctl-health.sh

Added API, client tests and sharness tests for GET /monitor/metrics/{metrics_type}
Fixes #587

Added tests for /monitor/metrics/{metrics_type}     

---

CHANGELOG.md

Changelog for 0.8.0 release

---

observations/config.go
observations/setup.go

* StatsReportingInterval -> ReportingInterval
* TracingSamplingProb -> SamplingProb
* TracingServiceName -> ServiceName
This is needed for #663

Rename observations Config fields

---

CHANGELOG.md

v0.9.0 changelog

---

adder/ipfsadd/add.go
cluster.go
consensus/raft/raft.go
package.json

Dependency alignment for libp2p-6.0.33, dag libraries and others

---

package.json

No more duplicates with protobuf
License: MIT

Update to libp2p-6.0.35 and general dep alignment

---

.travis.yml
README.md

Alignment with the rest of the projects. Plus coveralls is getting really annoying by commenting on pulls.

Move to codecov.io

---

package.json

Update libp2p et al. ..... again

---

package.json

Update libp2p to 6.0.38

---

api/rest/restapi_test.go

License: MIT
Signed-off-by: Alexey Novikov <alexey@novikov.io>

fix #645: Basic Authentication test in REST API

---

COPYRIGHT
LICENSE-APACHE
LICENSE-MIT
README.md

This removes the sign-off requirement.
License: MIT

Dual-license the codebase.

---

Dockerfile

add certs to Dockerfile

---

api/util.go

License: MIT
Signed-off-by: chenminjian <727180553@qq.com>

refact: remove duplicative package

---

.travis.yml
Makefile
add_test.go
cluster.go
cluster_config.go
cluster_test.go
clusterhost.go
config_test.go
consensus/crdt/consensus.go
ipfscluster_test.go
peer_manager_test.go
pnet_test.go

Waiting on additional fixes for #340.
(Related: #458)

Fix #340: Run tests with -race

---

api/types_test.go

add IPFSPinStatusFromString benchmark

---

pstoremgr/pstoremgr.go

Might add more here. Non critical for the moment.

Some more small fixes

---

cluster.go
cluster_config.go
cluster_config_test.go

Interval controlled by a pin_recover_interval option in the config.

Feat: regularly trigger "recover" automatically

---

cluster.go
consensus/raft/raft.go

This is mainly to illustrate https://github.com/ipfs/ipfs-cluster/issues/211#issuecomment-515831913

Make use of hRaft LeaderObservation type

---

add_test.go

The only way I can reproduce this failure is to reduce the delay.

Tests: AddLocal, increase delay

---

sharness/lib/test-lib.sh
sharness/t0052-service-state-export.sh
sharness/t0053-service-state-import.sh
sharness/t0054-service-state-clean.sh

I forgot to do this before merging #856 
There might be a way to not copy paste code but this is straightforward enough and the tests are quite old and probably need a rewrite anyways.

Sharness: run state import/export with both crdt and raft

---

config_test.go
consensus/raft/raft.go

Bets are on that tests will pass first time...

Fix #883: Tweak timeouts for better tests

---

add_test.go
api/add.go
cmd/ipfs-cluster-ctl/main.go
rpc_api.go

Added UserAllocations support for `add`

---

api/add.go
api/rest/restapi.go
api/types.go

This removes duplicated code to parse PinOptions.

Fix: consolidate parsing of PinOptions

---

api/ipfsproxy/config.go
api/ipfsproxy/config_test.go
api/ipfsproxy/ipfsproxy.go
api/ipfsproxy/ipfsproxy_test.go
logging.go

Same as API logs for Cluster REST APIs
https://github.com/ipfs/ipfs-cluster/issues/574

API logs for IPFS Proxy

---

api/rest/client/client.go
api/rest/client/transports.go
api/rest/restapi.go
go.mod
go.sum

Let's the client dial to a unix socket (server side works without changes).

RestAPI client: support unix sockets

---

cmd/ipfs-cluster-service/daemon.go
cmd/ipfs-cluster-service/main.go
cmdutils/cmdutils.go
cmdutils/configs.go
cmdutils/state.go

Service: extract some methods to cmdutils

---

cmd/ipfs-cluster-ctl/dist/LICENSE-APACHE
cmd/ipfs-cluster-ctl/dist/LICENSE-MIT
cmd/ipfs-cluster-service/dist/LICENSE-APACHE
cmd/ipfs-cluster-service/dist/LICENSE-MIT

These get packaged  with builds on dist.ipfs.io

Distribute the correct dual license with ctl and service

---

CHANGELOG.md
adder/adder.go
adder/ipfsadd/add.go
adder/sharding/dag.go
adder/sharding/dag_service.go
adder/sharding/shard.go
adder/util.go
api/rest/client/methods.go
api/rest/client/request.go
cluster.go
cluster_config.go
cmd/ipfs-cluster-follow/commands.go
cmd/ipfs-cluster-service/lock.go
cmdutils/cmdutils.go
ipfscluster.go
ipfsconn/ipfshttp/ipfshttp.go

fix: Fix typos

---

api/ipfsproxy/config.go
api/ipfsproxy/config_test.go
api/ipfsproxy/ipfsproxy.go
api/ipfsproxy/ipfsproxy_test.go
api/rest/client/client_test.go
api/rest/config.go
api/rest/config_test.go
api/rest/restapi.go
api/rest/restapi_test.go
cluster_config.go
cmd/ipfs-cluster-follow/commands.go
cmd/ipfs-cluster-service/main.go
cmd/ipfs-cluster-service/main_test.go
cmdutils/cmdutils.go
ipfscluster_test.go
ipfsconn/ipfshttp/ipfshttp_test.go
sharness/config/basic_auth/service.json
sharness/config/ssl-basic_auth/service.json
sharness/config/ssl/service.json
test/ipfs_mock.go

Taking over from #1002 
@RubenKelevra

add ipv6 listening addresses to the default config

---

LICENSE
LICENSE-APACHE
LICENSE-MIT
cmd/ipfs-cluster-ctl/dist/LICENSE
cmd/ipfs-cluster-follow/dist/LICENSE
cmd/ipfs-cluster-service/dist/LICENSE

Source: https://github.com/libp2p/go-libp2p-core/pull/116/commits/59df5e58a264aa479935ff5e23832de5ebe2d5d3

Chore: Add license file with URLS

---

cluster.go
clusterhost.go
consensus/crdt/consensus_test.go
go.mod
go.sum
ipfscluster_test.go
sharness/t0030-ctl-pin.sh

chore: update deps (dht)

---

cmd/ipfs-cluster-ctl/formatters.go

Manually tested by firing an ipfs cluster and build the cli utility

Fixes #998 Added object expiry time to pin ls cmd.

---

informer/disk/disk.go

Fix #1120: Do not let the size metric underflow uint.

---

api/ipfsproxy/config.go
api/rest/config.go
cluster_config.go
cmd/ipfs-cluster-service/daemon.go
config/config.go
config/config_test.go
config/util.go
consensus/crdt/config.go
consensus/raft/config.go
datastore/badger/config.go
informer/disk/config.go
informer/numpin/config.go
ipfsconn/ipfshttp/config.go
monitor/pubsubmon/config.go
observations/config.go
pintracker/stateless/config.go

print full working configuration at startup

---

cluster.go

We cannot rely on current pin allocations anymore since the allocations
may be follower peers that do not even handle alerts.
Instead, we assume that we are a trusted peer (because we are not in follower
mode), get all other trusted peers and act if we are the XOR-closest to the
CID.
This also means that replication-factor = 1 pins can be recovered too.

Fix #1064: Make the peer closest to the CID in charge of repinning

---

api/rest/client/methods_test.go
api/rest/restapi.go
api/types.go
cluster.go
cmd/ipfs-cluster-ctl/formatters.go
cmd/ipfs-cluster-follow/commands.go
cmdutils/state.go
ipfscluster_test.go
pintracker/optracker/operationtracker.go
pintracker/pintracker_test.go
pintracker/stateless/stateless.go
test/rpc_api_mock.go

* Fix #1013 
* Speed up and allow fully offline list (including with IPFS offline)

Improvements to ipfs-cluster-follow * list

---

Dockerfile
Dockerfile-bundle
Dockerfile-test
clusterhost.go
go.mod
go.sum

Deprecate secio to noise and fix docker build.

---

cmd/ipfs-cluster-ctl/Makefile
cmd/ipfs-cluster-follow/Makefile
cmd/ipfs-cluster-service/Makefile

Kudos to https://github.com/ipfs/distributions/pull/314

Switch to building with -trimpath instead of asm and gc trimpath flags

---

CHANGELOG.md
go.mod
go.sum

And bump go-ds-crdt and ipfs-lite dependencies.

Changelog for v0.13.2

---

adder/adder.go

This sets the "size" value to the FileSize() value when the CAR file's root
is a unixfs file. (Folders are not files, size will still be 0).

Fix #1362: Add "size" to response when adding CARs with a unixfs file root

---

pintracker/stateless/stateless.go

This is a follow up to #1360 which further optimizes StatusAll calls by
avoiding listing and filtering the cluster state when requesting status for
operations that should be direclty in the operation tracker because they are
ongoing (queued, pinning, unpinning, error).

pintracker: avoid listing the state unless necessary

---

cluster.go

On large pinsets this may take a very long time and prevents metrics and
re-boostrapping from starting, among other things. See bug description.
This lets watchPinset trigger an immediate RecoverAllLocal instead, but this
happens in its own goroutine and should allow everything else to start.

Fix #1436: Do not block peer startup waiting for RecoverAll

---

monitor/pubsubmon/pubsubmon.go

Before: receiving a metric from a peer <= 0.13.3 causes decoding error on logs.
Now: metric is correctly parsed and a warning message is printed once.

Fix #1409: Better support of metrics from older peers

---

api/rest/client/methods.go
api/rest/client/methods_test.go
cmd/ipfs-cluster-ctl/main.go

This commit updates the WaitFor helper code and the --wait flag behaviour.
Currently, when waiting for a CID to be pinned, it would wait until all
statuses report Pinned or Remote. If a peer is lagging behind and shows
"unpinned" for whatever reason, the wait will get stuck even if the item was
correctly pinned in the places it needs to.
The logic is now re-worked to allow waiting until replication_factor_min is fulfilled.
Fixes #1427

Change --wait behaviour to return on replication-factor-min

---

adder/adder_test.go

Adder: try to make test less flaky

---

api/common/api.go

They need to be handled directly by the CORS handler.
Fixes #1512

API: OPTIONS requests should bypass authentication

---

add_test.go
adder/single/dag_service.go

It is not good to add something locally only to pin it somewhere else:
* The locally used space is not GCed automatically or anything and is lost
* Pay the penalty of having to copy things somewhere else

Adder: adding with --local forcefully allocates the local peer to the pin

---

monitor/metrics/store.go
monitor/metrics/window.go
monitor/metrics/window_test.go

Follow up to #939. Fixes #1586.

monitor: Remove Distribution() method and test.

---

rpc_policy.go
rpcutil/policygen/policygen.go

RPC: Remove BlockPut from the policy

---

ipfsconn/ipfshttp/ipfshttp.go
pintracker/stateless/stateless.go

This fixes some issues on v1.0.0-rc4

Bug fixing for v1.0.0-rc4

---

docker-compose.yml

License: MIT
Signed-off-by: Sungyub NA <darkerkorean@gmail.com>

Fix: Update comment at docker-compose

---

pintracker/optracker/operation.go
pintracker/optracker/operationtracker.go

I believe this fixes the issue with some metrics like pinning going into
negative numbers ocassionally. Fixes #1702.

pintracker: fix some races resulting in wrong metric counts

---

ipfsconn/ipfshttp/ipfshttp.go
pintracker/optracker/operationtracker.go

According to https://pkg.go.dev/sync/atomic#pkg-note-BUG , the panic below might be produced by struct unaligned problem.

fix panic: unaligned 64-bit atomic operation on Linux@armv7

---

ipfsconn/ipfshttp/ipfshttp.go
pintracker/optracker/operationtracker.go

Add comments to struct fields that must be aligned.

---

cmd/ipfs-cluster-service/main.go
go.mod
go.sum

Provide access to some crdt-internal operations

service: add crdt info, mark-dirty, mark-clean commands

---

go.mod
go.sum

Update tar-utils to resolve a path traversal vulnerability

---

.github/workflows/tests.yml
cmd/ipfs-cluster-service/pebble_disabled.go
cmd/ipfs-cluster-service/pebble_enabled.go
datastore/pebble/config.go
datastore/pebble/pebble.go
ipfscluster_test.go
logging.go

* Make pebble default (badger3 as fallback for unsupported platforms)
* Better configurations defaults for Pebble

Pebble: make default

---

api/ipfsproxy/ipfsproxy.go

I am new to go, but for me this solves issue #1885 including missing pin status display in ipfs-go webui.

Add newline to json stream to pin/ls

---

.github/workflows/docker-image.yml
Dockerfile
docker/entrypoint.sh
docker/get-docker-tags.sh

General alignment with Kubo and other projects
- Switch to Alpine for final image
- Switch to Github Actions for building and pushing

Docker: support multiarch builds

---

ipfsconn/ipfshttp/ipfshttp.go

Kubo can listen on a unix socket instead of tcp. This allows talking to that in the same way that the API client already supported talking to a cluster daemon listening on unix sockets.

Fix #1999: Support talking to unix sockets in the ipfshttp connector

---

cluster_config.go
clusterhost.go
go.mod
go.sum
util.go

Same as corresponding IPFS Options
announce - the swarm addresses to announce to the network no_announce - swarm addresses not to announce to the network

Add Announce and NoAnnounce swarm options

---

api/ipfsproxy/ipfsproxy.go

These two changes were made to the ipfshttp connector already.
First, node_multiaddress should not be pre-resolved, only using the first result of the resolution.
Second, we should support node_multiaddresses that are pointing to unix sockets, as the kubo daemon can listen to requests that way and it is better than tcp for local requests.

ipfsproxy: do not pre-resolve dns addrs / support api over unix sockets

---

cmd/ipfs-cluster-ctl/main.go

https://github.com/ipfs-cluster/ipfs-cluster/issues/1675

fixed the error code parsing when context cancelled or deadline exceeded

---

cluster.go
cluster_config.go
cluster_test.go
cmd/ipfs-cluster-ctl/main.go
consensus/raft/config.go
docker-compose.yml

fix some minor issues in comments

chore: fix some minor issues in comments
