- README.md
- cluster.go
- cluster_test.go
- config.go
- config_test.go
- consensus.go
- consensus_test.go
- ipfs-cluster-service/main.go
- ipfs_http_connector.go
- ipfs_http_connector_test.go
- ipfscluster.go
- ipfscluster_test.go
- map_pin_tracker.go
- raft.go
- rest_api.go
Fixes #22 
* Use multiaddresses
* Give more meaningful errors if a config is badly formatted
* Be more clever as where to place the data folder
* Bonus: workaround tests randomly failing
> Fix #22: Address feedback regarding configuration

- cluster.go
- cluster_test.go
- ipfs-cluster-ctl/main.go
- ipfs_http_connector.go
- ipfs_http_connector_test.go
- ipfscluster.go
- ipfscluster_test.go
- map_pin_tracker.go
- rest_api.go
- rest_api_test.go
- rpc_api.go
- rpc_api_test.go
* Syncing all Cids should use PinLs
* Renamed API methods, Internal types and endpoints to something I find more consistent
* Moved Recover() ops to it's own endpoint and allow only on single CID.
* Support all this in cluster-ctl
> Fixes #8: Reworking PinTracker (sync/recover ops)

- README.md
- ROADMAP.md
- architecture.md
- captain.log.md
- cluster.go
- cluster_test.go
- config.go
- consensus.go
- ipfs-cluster-ctl/main.go
- ipfs_http_connector.go
- ipfs_http_connector_test.go
- ipfscluster.go
- ipfscluster_test.go
- ipfsmock_test.go
- rest_api.go
- rest_api_test.go
- rpc_api.go
- rpc_api_test.go
I have renamed "members" to "peers".
Added IPFS daemon ID and addresses to the ID object and
have Peers() return the collection of ID() objects from the cluster.
#15
> Fix #15: Peers() provides lots of information now

- ipfs_http_connector.go
- ipfs_http_connector_test.go
- ipfsmock_test.go
The proxy now mimics the IPFS daemon for these commands, except
the requests trigger cluster operations.
#9
> Fix #9: Add customHandlers for pin/add pin/rm and pin/ls

- README.md
- architecture.md
- cluster.go
- cluster_test.go
- config.go
- config_test.go
- consensus.go
- consensus_test.go
- ipfs-cluster-ctl/main.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- logging.go
- map_pin_tracker.go
- peer_manager.go
- peer_manager_test.go
- raft.go
- rest_api.go
- rest_api_test.go
- rpc_api.go
- rpc_api_test.go
- util.go
Fixes #10 
This commit adds PeerAdd() and PeerRemove() endpoints, CLI support,
tests, docs... Peer management is a delicate issue because of how the consensus
works underneath and the places that need to track such peers.
When adding a peer the procedure is as follows:
* Try to open a connection to the new peer and abort if not reachable
* Broadcast a PeerManagerAddPeer operation which tells all cluster members
to add the new Peer. The Raft leader will add it to Raft's peerset and
the multiaddress will be saved in the ClusterPeers configuration key.
* If the above fails because some cluster node is not responding,
broadcast a PeerRemove() and try to undo any damage.
* If the broadcast succeeds, send our ClusterPeers to the new Peer along with
the local multiaddress we are using in the …
> PeerAdd and PeerRemove() functionality

- README.md
- architecture.md
- cluster.go
- config.go
- config_test.go
- consensus.go
- consensus_test.go
- debug.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- logging.go
- map_state.go
- nodebug.go
- peer_manager.go
- peer_manager_test.go
- raft.go
- rpc_api.go
- silent.go
- util.go
This is the third implementation attempt. This time, rather than
broadcasting PeerAdd/Join requests to the whole cluster, we use the
consensus log to broadcast new peers joining.
This makes it easier to recover from errors and to know who exactly
is member of a cluster and who is not. The consensus is, after all,
meant to agree on things, and the list of cluster peers is something
everyone has to agree on.
Raft itself uses a special log operation to maintain the peer set.
The tests are almost unchanged from the previous attempts so it should
be the same, except it doesn't seem possible to bootstrap a bunch of nodes
at the same time using different bootstrap nodes. It works when using
the same. I'm not sure this worked before either, but the code is
simpler than recursively contacting …
> Fix #24: Auto-join and auto-leave operations for Cluster

- api/types.go
- cluster.go
This fixes two small issues I watched during the demo the other day, mostly cosmetic:
* duplicate listen multiaddresses in the peer information
* timestamps shown in different timezones in the pin status information
Just checking that tests pass
> Small fixes

- cluster.go
- cluster_test.go
- config.go
- config_test.go
- ipfs-cluster-service/main.go
- ipfscluster_test.go
- peer_monitor.go
- peer_monitor_test.go
An initial, simple approach to this. The PeerMonitor will
check its metrics, compare to the current set of peers and put
an alert in the alerts channel if the metrics for a peer have expired.
Cluster reads this channel looking for "ping" alerts. The leader
(because that's the monitor here metrics are pushed from everywhere)
then reads the alerts and triggers repins in all the Cids allocated to
a given peer.
License: MIT
> Issue #45: Detect expired metrics and trigger re-pins

- README.md
As the time of this PR, the install locations are not yet ready, but will be when I merge.
@brainstorm how do the docker instructions look to you? Anything you would improve?
> Add docker and dist.ipfs.io install methods to README

- cluster.go
- ipfscluster_test.go
This is a better approach than broadcasting everything all the time
(see 6ee0f3bead62ffe69f5343540db3771bf4be35ac). A couple of delays
have been touched in order to make tests less likely to fail randomly.
(Issue #65).
I have manually run the travis tests for the branch 5 times and got it green everytime. Finger crossed.
License: MIT
> Address randomly failing tests. Improve metrics broadcasts.

- cluster.go
- ipfscluster.go
- state/mapstate/map_state.go
- state/mapstate/map_state_test.go
- state/mapstate/migrate.go
This adds snapshot and restore methods to state and uses the snapshot
one to save a copy of the state when shutting down. This is WIP on migrations but adds
at least a user-readable view of the state.
License: MIT
> Issue #51: Save a backup on shutdown

- ipfsconn/ipfshttp/ipfshttp.go
- pintracker/maptracker/maptracker.go
- pintracker/maptracker/maptracker_test.go
This is significantly faster for pins that don't exist.
License: MIT
> Use "pin ls --type=recursive $pin" when checking if a pin exists

- cluster.go
- cluster_test.go
- coverage.sh
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- rpc_api.go
- test/ipfs_mock.go
- test/rpc_api_mock.go
This runs ipfs swarm connect to the reported ipfs daemon addresses for all peers in the cluster, every time a cluster node comes up. It ignores any errors (which will happen).
> Fixes #16: trigger ipfs swarm connect to other ipfs nodes in the cluster

- allocator/ascendalloc/ascendalloc.go
- allocator/ascendalloc/ascendalloc_test.go
- cluster_test.go
- config.go
- config_test.go
- informer/disk/disk.go
- informer/disk/disk_test.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- logging.go
- rpc_api.go
- test/ipfs_mock.go
- test/rpc_api_mock.go
The disk informer uses "ipfs repo stat" to fetch the RepoSize value and
uses it as a metric.
The numpinalloc allocator is now a generalized ascendalloc which
sorts metrics in ascending order and return the ones with lowest
values.
License: MIT
> Fix #49: Add disk informer

- cluster.go
- config.go
- pintracker/maptracker/maptracker.go
It makes a pin ls requests to ipfs and makes sure the pin tracker is
up to date.
#88 
License: MIT
> Fix #88: Run SyncAllLocal() regularly on peers.

- api/restapi/restapi.go
- ipfs-cluster-ctl/formatters.go
The ReadTimeout for the API was the same as for RPC. So the error
did not have time to be correctly returned to the client.
License: MIT
> Fixes #100: EOF responses when cluster peer is not responding

- .travis.yml
- ipfs-cluster-ctl/main.go
- sharness/run-sharness-tests.sh
- sharness/t0010-ctl-basic-commands.sh
I've added `make sharness` to the travis yml and fixed the issue with the `ipfs-cluster-ctl`'s help text being over 80 characters.  Although things look good when I build `ipfs-cluster-ctl` manually I have had some issues with install building the correct version with the modified help text, and this may still be a problem.
> Travis sharness

- cluster.go
- docs/ipfs-cluster-guide.md
- ipfscluster_test.go
- monitor/basic/peer_monitor.go
- peer_manager_test.go
- util.go
PeerRm now triggers re-pinning of all the Cids allocated to
the removed peer.
#86 
License: MIT
> Re-allocate pins on peer removal

- Makefile
> Update gx to v0.12.0 and gx-go to v1.5.0

- ipfs-cluster-ctl/formatters.go
- ipfs-cluster-ctl/main.go
It seems that urfave/cli acts differently handling Description and Usage
depending on whether it is dealing with a command or a subcommand.
This fixes most of these issues, as well as the commands output which was
printing some blank lines.
License: MIT
> improve ipfs-cluster-ctl command help.

- config.go
- pnet_test.go
Small update to allow empty cluster secret for starting cluster on unprotected network.
> Allow empty cluster secret, update test to reflect this.

- cluster.go
- config.go
- consensus/raft/raft.go
- ipfs-cluster-service/main.go
We no longer set ConsensusDataFolder. We leave it empty (and ommited from the
configuration). When not set, it will take the path from which the configuration
file was read and use an "ipfs-cluster-data" subfolder in that path.
When set, the behaviour is just as before (ensures backwards compatiblity).
This will facilitate re-use of configuration files, for example, when mounting
them inside docker.
#97 
License: MIT
> Fix #97: Assume default DataFolder as subfolder to config folder when empty

- api/restapi/restapi.go
- api/restapi/restapi_test.go
- config.go
- ipfs-cluster-ctl/main.go
- ipfs-cluster-service/main.go
This PR addresses the issue https://github.com/ipfs/ipfs-cluster/issues/120. The current implementation builds, but has not yet been tested. The default TLS configuration used was copied from https://github.com/denji/golang-tls#perfect-ssl-labs-score-with-go and has not yet been verified outside of that source.
> WIP: HTTPS API endpoint support

- config.go
- ipfs-cluster-service/main.go
Also, omit these keys in JSON generation when they are empty.
License: MIT
> Rename TLS configuration options and set JSON key

- ipfs-cluster-service/main.go
This resolves https://github.com/ipfs/ipfs-cluster/issues/136. It also renames the `generateSecret` variable used in `ipfs-cluster-service/main.go:initConfig()` to `customSecret` to keep it consistent with the way `initConfig()` is called (less confusing to understand for newcomers, I think).
> Distinguish unset/empty cluster secret; also rename generateSecret -> customSecret

- allocator/ascendalloc/ascendalloc.go
- allocator/ascendalloc/ascendalloc_test.go
- allocator/descendalloc/descendalloc.go
- allocator/descendalloc/descendalloc_test.go
- allocator/util/metricsorter.go
- cluster_test.go
- informer/disk/disk.go
- informer/disk/disk_test.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- peer_manager_test.go
- rpc_api.go
- test/rpc_api_mock.go
Currently a WIP, but looking for feedback on implementation. I've added a `disk.NewInformerWithMetric(metric string)` function that supports `"disk-reposize"` and `"disk-freespace"` metrics (values checked in `setupAllocation()`, may want to check in `disk.NewInformerWithMetric()` instead). I think the disk Informer impl is fairly clean and makes it easy to add new metrics (simply by adding an entry to the `nameToRPC` map), but let me know what you think @hsanjuan.
TODO:
> `FreeSpace` allocation metric impl

- README.md
- docs/HOWTO_build_and_update_a_cluster.md
Fixed links in documentation to cluster secret initialization info.
Thanks for pointing this out @ZenGround0!
> Updated links to cluster secret info in docs

- sharness/lib/test-lib.sh
- sharness/t0020-service-basic-commands.sh
- sharness/t0030-ctl-pin.sh
Additionally I found that my system need `ps -a` in order to register that ipfs container was already running and prevent an initialization failure.
> Sharness Test Fix: Moving exec call to sh as bash is deprecated in go-ipfs

- ipfs-cluster-ctl/main.go
An error check is missing and this triggers panics when a response is nil
> Fix #182: Check request error in cluster-ctl

- ipfs-cluster-service/main.go
Shows an error when running cluster with an unknown subcommand.
Renames "ipfs-cluster-service run" to "ipfs-cluster-service daemon" which
is consistent with go-ipfs and paves ground for #153.
License: MIT
> ipfs-cluster-service: Do not run with unknown subcommands

- Dockerfile
- Dockerfile-test
- Dockerfile-test-busybox
- cluster_config.go
- docker/cluster-restart.sh
- docker/entrypoint.sh
- docker/random-killer.sh
- docker/random-stopper.sh
- docker/test-entrypoint.sh
- docker/wait-killer-stopper.sh
After changes on how the final docker image for go-ipfs is generated,
our Dockerfiles failed to build.
The new version is inspired on go-ipfs Dockerfile. It takes advantage
of docker >= v17.06 which allows multi-stage Dockerfiles with
several FROM directives and COPY --from. This allows build freely on a
first stage, without thinking of cleaning up, and then just copy the
final artifacts to a second, minimal image.
The Dockerfile-test is similarly updated. Minor changes have been
applied to the entrypoints.
License: MIT
> Fix #154: Update Dockerfiles

- cluster_config.go
- cluster_config_test.go
> Fix #203: Assign peers and bootstrap when parsing the configuration

- Dockerfile
- Dockerfile-test
- docker/entrypoint.sh
- docker/test-entrypoint.sh
This used to work. Even if it's been surfaced by 4a8759939 we were
extensively testing the Dockerfile before that release.
License: MIT
> Fix #216: Docker does not like an env variable in CMD (anymore?)

- cluster.go
- config/config.go
- config/util.go
- config_test.go
- consensus/raft/config.go
- consensus/raft/config_test.go
- consensus/raft/consensus.go
- consensus/raft/consensus_test.go
- consensus/raft/log_op.go
- consensus/raft/log_op_test.go
- consensus/raft/logging.go
- consensus/raft/raft.go
- debug.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- package.json
- peer_manager.go
- peer_manager_test.go
- rpc_api.go
- test/rpc_api_mock.go
The main differences is that the new version of Raft is more strict
about starting raft peers which already contain configurations.
For a start, cluster will fail to start if the configured cluster
peers are different from the Raft peers. The user will have to
manually cleanup Raft (TODO: an ipfs-cluster-service command for it).
Additionally, this commit adds extra options to the consensus/raft
configuration section, adds tests and improves existing ones and
improves certain code sections.
License: MIT
> Fix #139: Update cluster to Raft 1.0.0

- snap/patches/snap-home.patch
- snap/snapcraft.yaml
This package will let you publish the latest ipfs-cluster in the Ubuntu store, and from there reach many users on all the supported Ubuntu versions, and Linux distributions. You just have to go follow https://tutorials.ubuntu.com/tutorial/continuous-snap-delivery-from-travis-ci and enable the automated continuous delivery.
> Add the packaging metadata to build the ipfs-cluster snap

- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- test/ipfs_mock.go
Up to now, we hardcoded progress to "false" in the proxy, regardless
of what the original request said. We now leave it as it is, and
just ignore any progress updates when processing the response.
Since the response is buffered and sent back all together, they are
still useless, but at least the clients (ipfs cli) won't show a 0%
progress bar when successfully adding a file.
License: MIT
> Fix #224: Better handling of progress updates when proxy-adding file

- consensus/raft/data_helper.go
- consensus/raft/data_helper_test.go
- consensus/raft/raft.go
This commit changes the way that consensus.Clean() works. Before
it deleted the whole data folder. Now it renames it as <name>.old.0
and leaves it. When Clean() is called again, it renames <name>.old.0
as <name>.old.1, and the actual data becomes <name>.old.0. Higher number
means older. The number of backups is fixed to 5. When 5 backups exists
and a new one comes up again, the last one is discarded.
License: MIT
> Raft: do not ever remove state, rename it and leave it around

- api/types.go
- api/types_test.go
- cluster.go
- cluster_config.go
- config/config.go
- consensus/raft/config.go
- consensus/raft/consensus.go
- consensus/raft/consensus_test.go
- consensus/raft/log_op.go
- debug.go
- ipfs-cluster-ctl/formatters.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- monitor/basic/peer_monitor.go
- peer_manager.go
- peer_manager_test.go
- rpc_api.go
- test/rpc_api_mock.go
This change removes the duplicities of the PeerManager component:
* No more commiting PeerAdd and PeerRm log entries
* The Raft peer set is the source of truth
* Basic broadcasting is used to communicate peer multiaddresses
in the cluster
* A peer can only be added in a healthy cluster
* A peer can be removed from any cluster which can still commit
* This also adds support for multiple multiaddresses per peer
License: MIT
> Fix #219: WIP: Remove duplicate peer accounting

- cluster.go
- ipfsconn/ipfshttp/config.go
- peer_manager_test.go
- util.go
SwarmConnect on the ipfs connector calls rpc Peers() which
requests IDs for every peer member. If that peer member
is booting, it might get the request after RPC is setup
but before consensus is initialized. In which case
a panic happens. Probability that this happens is small, but still.
Also increase the connect swarms delay to 30 seconds, which
should be a bit longer than the default wait_for_leader timeout,
otherwise we might connect swarms while there's not even a leader.
License: MIT
> cluster: safeguard consensus not set when calling ID

- .travis.yml
I didn't escape the arch variable in the loop of the script to build the snap.
```
$ sudo docker run -t snapcore/snapcraft sh -c "for var in amd64 i386 armhf arm64; do echo $var; done"
$ sudo docker run -t snapcore/snapcraft sh -c "for var in amd64 i386 armhf arm64; do echo \$var; done"
amd64
i386
armhf
arm64
```
> Escape the variable in the snapcraft loop

- Makefile
- api/rest/client/.travis.yml
- api/rest/client/README.md
- api/rest/client/client.go
- api/rest/client/client_test.go
- api/rest/client/methods.go
- api/rest/client/request.go
- api/rest/client/tls.go
- ipfs-cluster-ctl/formatters.go
- ipfs-cluster-ctl/main.go
- ipfs-cluster-service/lock.go
- ipfs-cluster-service/main.go
This adds the pakage api/rest/client which implements a go-client
for the REST API component. It also update the ipfs-cluster-ctl
tool to rely on it.
Originally, I wanted this to live it in it's own separate repository,
but the api client uses /api/types.go, which is part of cluster.
Therefore it would need to import all of cluster as a dependency.
ipfs-cluster-ctl would also need to import go-ipfs-cluster-api-client
as a dependency, creating circular gx deps which would be a mess to
maintain.
Only the splitting of cluster in multiple repositories (at least for
api, rest, ipfs-cluster-ctl, rest/client and test) would allow better
dependency management by allowing rest/client and the ctl tool
to only import what is needed, but this is something which brings
maintenance costs and can …
> Fix #260: Add REST API client and use it in ipfs-cluster-ctl

- ipfs-cluster-ctl/dist/README.md
> Fix #178: Document exit status for ipfs-cluster-ctl

- cluster.go
- consensus/raft/consensus.go
- consensus/raft/raft.go
- ipfs-cluster-service/main.go
- version.go
The --version flag is default from our cli library so I left that. The
version subcommand prints only the version number + the short commit
so it's a bit more easy to parse.
I have additionally reduced the amount of output on start up by converting
some messages to debug. I wish there was a level between INFO and DEBUG
though.
Fixes #201 
License: MIT
> cluster-service: add version subcommand and change some startup logging

- state/mapstate/migrate.go
This is meant to address issue #230.  It implements the ideas put forward there to help ease the development of state migration changes when format versions increase.  With so few supported versions at present the overhead may seem unnecessary but it should start obviously paying off when we get to version ~10.
@hsanjuan there is still a lot of updating required in the case of a version increase.  Suggestions to improve this are particularly welcome.
> Generalize migration process

- .travis.yml
- api/rest/restapi.go
- consensus/raft/raft.go
- state/mapstate/map_state.go
Still thinking if worth to do retry-ing or something like that.
Did we ever try to Snapshot after shutdown?
There doesn't seem to be a way to tell raft to not take any more updates so this is a best effort...
> Fix #275: Attempt to wait for updates when shutting down

- ipfsconn/ipfshttp/ipfshttp.go
- sharness/lib/test-lib.sh
- sharness/t0020-service-basic-commands.sh
- sharness/t0025-ctl-status-report-commands.sh
- sharness/t0030-ctl-pin.sh
- sharness/t0040-ssl-simple-exchange.sh
- sharness/t0041-ssl-enforcement.sh
- sharness/t0042-basic-auth.sh
- sharness/t0043-ssl-basic-auth.sh
- sharness/t0050-service-state-upgrade-from-current.sh
- sharness/t0051-service-state-upgrade-from-old.sh
- sharness/t0052-service-state-export.sh
- sharness/t0053-service-state-import.sh
- sharness/t0054-service-state-clean.sh
Recent sharness failures prompted more investigation.  In particular sharness `cleanup` does not run cleanup functions on failure (see here: https://github.com/chriscool/sharness/blob/master/sharness.sh#L763).  To ensure isolation among test failures we need reliable teardown of ipfs and cluster between each testfile so now the cleanup functions are run directly before test_done.  
Error messages are also slightly improved.
The current `test-lib.sh` already ensures that there is no data folder with `rm -rf ipfs-cluster-data` after the config folder is created.
Altogether this should close #181.
> Harden Sharness

- ipfs-cluster-service/state.go
It was comparing state.GetVersion() against state.Version, which
is the same, instead of against mapstate.Version, which is the
constant for the current Version.
It was also returning a nil error, as the scope of the variable
assigned was not that of the outer level.
License: MIT
> Fix: validateState does not detect different state versions

- ipfs-cluster-service/main.go
- ipfs-cluster-service/state.go
- state/mapstate/map_state.go
Feat #300 -- `--upgrade` flag for automatically running upgrades when launching service
Fix #296   -- current state formats no longer cause upgrades.  No error but a warning
Feat #298 -- `ipfs-cluster-service state version` reports the mapstate version used by this cluster binary
> Three small state features

- api/rest/client/request.go
- api/rest/restapi.go
- cluster_test.go
- ipfscluster.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- ipld-importer/import.go
- rpc_api.go
- test/cids.go
- test/ipfs_mock.go
Minimal code for adding files to ipfs via ipfs-cluster-ctl add.  Restapi now uses importToChannel and calls IPFS block/put on outgoing dag nodes' raw blocks' bytes.  Error checking and context cancellation could use some work.  Garbage collection is not considered.  As we are using block put the added data won't survive an ipfs gc.  
No golang tests yet, but I have tested by hand with complex directories (some paths up to 5 layers deep).  And things generally look good.  More extensive and precise tests to follow.
License: MIT
Signed-off-by: Wyatt Daviau <wdaviau@cs.stanford.edu>
> Add files to calling cluster peer's ipfs daemon

- ipfs-cluster-ctl/main.go
@hsanjuan @ZenGround0 Thoughts on the naming of the shortflag `-nostat`?
> ipfs-cluster-ctl cmd: add no-status flag to pin add/rm

- ipfs-cluster-service/lock.go
> lock file location printed in log

- informer/disk/disk_test.go
- informer/numpin/numpin_test.go
- package.json
- rpc_api.go
- test/rpc_api_mock.go
- test/test_test.go
Bubble up libp2p 5.0.14 across all deps.
@ZenGround0 this should be what ipfs uses right now so it shoud be OK with your sharding rebase.
Note: contexts introduced but simply ignored. Will start not ignoring them in other PRs. Here it was just a side effect.
> Update libp2p and deps to correct versions

- cluster.go
- consensus/raft/logging.go
- docs/ipfs-cluster-guide.md
This will display a few hints when consensus fails to start.
If consensus doesn't start (normally WaitForLeader times out),
it's because of libp2p not being able to reach other peers.
I have reworked the raft-logging de-duplicator part to keep a list of last messages and not spam the logs all the time with the same things.
Before:
```
23:45:14.802  INFO    cluster: IPFS Cluster v0.3.4-c276c31a listening on: cluster.go:90
23:45:14.802  INFO    cluster:         /ip4/127.0.0.1/tcp/10096/ipfs/Qma7KpVhrTgkdUxBanyVSffjydx9dceDXDz1K8GzspB7me cluster.go:95
23:45:14.802  INFO    cluster:         /ip4/192.168.123.103/tcp/10096/ipfs/Qma7KpVhrTgkdUxBanyVSffjydx9dceDXDz1K8GzspB7me cluster.go:95
23:45:14.806  INFO    restapi: REST API: /ip4/127.0.0.1/tcp/10094 restapi.go:285
23:45:14.806  INFO …
```
> Fix #167: Useful messages when consensus doesn't start

- ipfs-cluster-service/dist/README.md
This is also reflected in the other documentations.
License: MIT
Signed-off-by: racin
> Documentation: Can't get peers to connect without /ipfs/ before <id>.

- api/rest/client/methods.go
- ipfs-cluster-ctl/main.go
- sharness/t0030-ctl-pin.sh
Putting this up early, as there are a few things I am unsure about.
1) api/rest/client/methods.go:193
```diff
+				// TODO(ajl): check I can override api.TrackerStatusBug here for
+				// error reporting purposes or return an error chan,
+				// not sure which is the best option.
+				statusCh <- api.TrackerStatusBug
```
2) The use of `goto` to simplify the for loop wait logic. See api/rest/client/methods.go:201 and api/rest/client/methods.go:207.
3) The `pin` test works but not in current configuration combined with the `unpin` test. 
Thoughts and suggestions would be greatly appreciated 👍
> rest/client: Add WaitFor utility function

- pintracker/maptracker/maptracker.go
First bug from testing 0.3.5-rc1 (good that I did an rc).
@ZenGround0 the pin tracker will need some changes with sharding... probably should carry the pin types of the tracked things.
> Fix: Recover does not pin recursively

- api/types.go
The rest/client does things like "return id.ToID(), err" which is nice.
But when there's an error the ID has Cid set to nil etc. This is now
causing error messages on the console which are very misleading because
they do not correspond to the actual error of the request.
License: MIT
> api/types: do not print some errors

- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- api/types.go
- api/types_test.go
- cluster.go
- cluster_test.go
- consensus/raft/consensus_test.go
- consensus/raft/log_op.go
- ipfs-cluster-ctl/formatters.go
- ipfs-cluster-ctl/main.go
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- package.json
- pintracker/maptracker/maptracker.go
- rpc_api.go
- sharder/clusterdag.go
- sharder/sharder_test.go
- state/mapstate/migrate.go
- test/cids.go
- test/ipfs_mock.go
- util.go
@hsanjuan This is my stab at the new state format after our discussion last week.  Could I get some feedback on the representation of the different "PinTypes"?  Some questions:
* Are you in favor of the datatype's structure?
* Are any of the new names used confusing?
* Are you ok with a single Child field (queries for children of metadata nodes must go through ipfs)?
* Is the pattern of updating the Log, to account for the fact that shard pins will only know of their parents after they are pinned, acceptable?
* Any problems with the addition of a new trackerStatus to denote metapins?  Local and remote didn't seem quite right because potentially some shards are local and some are remote.
* should the `status` command display to the user a field to distinguish if a pin is metadata (cdag or …
> State change for sharding support

- api/rest/client/methods.go
- api/rest/client/methods_test.go
- ipfs-cluster-ctl/main.go
@lanzafame this was very visibly not working when I tried it. Please test a bit better next time.
>  Fix: --wait flag in ipfs-cluster-ctl and WaitFor function

- cluster.go
- cluster_config.go
- cluster_config_test.go
- config_test.go
- ipfscluster_test.go
This PR adds the option `disable_repinning` along with its default value, and test values. `repinFromPeer` returns if this option is true.
I'm having problems with running the tests to ensure everything is passing. I get `ipfscluster_test.go:69: bootstrap unsuccessful`, does anyone know what might be the cause?
> Add disable_repinning cluster option

- docs/ipfs-cluster-guide.md
`basic_auth_credentials` in `api` part of the config accepts a map, with username as key and password as value.
> doc: fix basic_auth_credentials format in config

- ipfs-cluster-service/main.go
> Fix: do not fail when running daemon --upgrade and no state exists

- ipfs-cluster-ctl/main.go
This uses the PeerAdd endpoint which should NOT be used as the current
workflow states that the way to adding peers is bootstrapping.
Adding peers manually with this endpoint leads to split-head states very
easily. The fact that this operation is visible in ipfs-cluster-ctl
is only leading the users to bad places.
License: MIT
> ipfs-cluster-ctl: do not provide "peers add"

- api/rest/config.go
> Fix: do not generate "listen_multiaddress" deprecated option in config

- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- test/ipfs_mock.go
The extractCid function was added to enable the extraction of
a cid argument from either the url path or query string.
This puts the proxy behaviour on par with the current IPFS API.
The function does rely on the fact that ipfs-cluster doesn't
intercept any command that has more than one subcommand.
If that changes, this function will have to be updated.
License: MIT
> ipfsconn/ipfshttp: handle cid args passed in url path correctly

- ipfscluster_test.go
- pintracker/maptracker/maptracker.go
When StateSync() runs and triggers Untrack() on items
that have just been removed from the state but on which
Untrack() is underway, the operation tracker would be
reset to phase queued and in some cases stay so.
Also happened for Track()
This caused failures of TestClustersPin as SyncStatus()
is triggered regularly while Tracks() and Untracks() happen.
License: MIT
> Fix #408: Race condition when StateSync runs

- cluster.go
- cluster_test.go
- ipfs-cluster-service/daemon.go
- rpc_api.go
- test/rpc_api_mock.go
This commit:
* Does not collect and return changed items when doing StateSync (they are
not used)
* Removes the StateSync RPC method (no longer used)
* Uses tracker.StatusAll() rather than requesting Status on each Cid (should
be faster with upcoming pintracker)
* Does not launch a go-routine to track every item. Track is an async
operation. This likely causes 1000s goroutines to be started with no good
reason.
License: MIT
> StateSync(): some improvements

- ipfs-cluster-service/daemon.go
Fixes #423 by running `locker.tryUnlock()`
License: MIT
Signed-off-by: Lilith McMullen <iggnsthe@live.com>
> fix #423: Remove lock file when daemon force quits

- package.json
Among other things, this fixes race condition test failures in libp2p and
random panics in go-log.
License: MIT
> Go-libp2p: update to 5.0.17

- api/types.go
Otherwise, they are int. This forces API users to do manual variable
type declaration when initializing something to one of these constants
License: MIT
> Fix: API constants should explicit their type

- Dockerfile
- Dockerfile-test
- ipfsconn/ipfshttp/ipfshttp.go
- pstoremgr/pstoremgr.go
> Fix #462: Support DNS multiaddresses for node_multiaddress

- api/rest/client/client.go
- api/rest/client/client_test.go
- api/rest/client/transports.go
- ipfs-cluster-ctl/main.go
This removes PeerAddr and uses APIAddr directly, figuring out if it is
a Peer multiaddress or not.
PeerAddr is actually kept for compatiblity.
It also fixes a bad panic when resolving returned 0 results
License: MIT
> Feat/rest/client: auto-handling of libp2p endpoints

- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- cluster.go
- package.json
- peer_manager_test.go
- pnet_test.go
- rpc_api.go
- test/rpc_api_mock.go
This uses go-libp2p-kad-dht as routing provider for the Cluster Peers.
This means that:
* A cluster peer can discover other Cluster peers even if they are
not in their peerstore file.
* We remove a bunch of code sending and receiving peers multiaddresses
when a new peer was added to the Cluster.
* PeerAdd now takes an ID and not a multiaddress. We do not need to
ask the new peer which is our external multiaddress nor broadcast
the new multiaddress to everyone. This will fix problems when bootstrapping
a new peer to the Cluster while not all the other peers are online.
* Adding a new peer does not mean to open connections to all peers
anymore. The number of connections will be made according to the DHT
parameters (this is good to have for future work)
The that detecting a peer addition in …
> Feat: Enable DHT-based peer discovery and routing for cluster peers

- cluster.go
- consensus/raft/consensus.go
- ipfscluster_test.go
- package.json
- pintracker/stateless/stateless_test.go
~~As pointed out in #340, still some failures coming from go-logging.~~
This fixes some of the data races identified when running with `-race`. Unfortunately, there are still data races in libp2p that we cannot take care of for the moment.
> Issue #340: fix some data races

- peer_manager_test.go
This uses Join rather than PeerAdd. Join ensures a DHT bootstrap
after successfully joining.
License: MIT
> Fix: TestClustersPeerRejoin was failing a lot since DHT feature.

- api/types.go
- cluster_test.go
- informer/disk/config.go
- informer/disk/disk.go
- informer/disk/disk_test.go
- ipfscluster.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- package.json
- rpc_api.go
- test/rpc_api_mock.go
Removes IPFSRepoSize and IPFSFreeSpace methods, consolidates them in IPFSRepoStat().
#466
> Fix #466: Hijack repo/stat in the proxy and return aggregates from the cluster

- Makefile
> Gx-go 1.8.0 it's WAY faster.

- Makefile
This PR adds a single make target that can run and check if I am
ready to push my PR, i.e, `make prcheck`
Fixes #536
> Issue #536 New make target for PR check

- .gitignore
- Dockerfile
- Makefile
By using gx install --local, deps are copied into
the build context and therefore only stale deps
will get pulled from the network on image build.
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/ipfs/ipfs-cluster/529)
> speed up building docker image

- cluster.go
- cluster_test.go
- ipfs-cluster-service/main.go
- ipfscluster.go
- ipfscluster_test.go
- package.json
- release.sh
- version.go
This patch modifies the RPC protocol tag to use Major and Minor parts of the
version and not all of it.
This means all peers on the 0.5.x can run in the same cluster.
As cluster has become more mature and I see less risks in letting peers from
similar versions run together. This is useful when upgrading too.
License: MIT
> Allow running peers with different cluster versions in the same cluster

- add_test.go
- cluster.go
- rpc_api.go
> Fix #543: Use only healthy peers when adding everywhere (+tests)

- api/rest/client/client.go
- api/rest/client/client_test.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/client/request.go
- api/rest/client/transports.go
- cmd/ipfs-cluster-ctl/main.go
- package.json
This PR addresses https://github.com/ipfs/ipfs-cluster/issues/447
I'm relatively new to Go and it's concept of interfaces, so if I'm doing this all wrong, don't hesitate to tell me so :slightly_smiling_face: 
In creating the new interface at `api/rest/client_interface/client_interface.go`, I had to move the definition of the `StatusFilterParams` type out of `api/rest/client/methods.go`, and into `api/types.go`, so that it could be used both in the new interface, and in the current client implementation.
I wasn't sure where to *use* the new interface. I looked for places that `c *Client` is being used that could instead use the interface. I ended up changing the tests in `methods_test.go`, does that sound right to you? Is there anywhere else I should be using this interface?
`make test` …
> First pass at creating a client interface ClientIface

- adder/adderutils/adderutils.go
- api/rest/restapi.go
- ipfsconn/ipfshttp/ipfshttp.go
This is a workaround to have clients behave properly with the /add
endpoint by asking them to close connections when done, effectively
disabling keep-alive for this.
This means we don't need to disable keep-alives fully on all servers,
since the rest of endpoints are not affected (they are not streaming
endpoints).
Reference https://github.com/ipfs/go-ipfs/issues/5168
License: MIT
> Fix #548: Re-enable keep-alives. Set Connection: Close when adding.

- api/rest/client/client.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- cmd/ipfs-cluster-ctl/main.go
#523 added a new interface and was written before the `*cid.Cid` to `cid.Cid` PR so rebasing didn't update anything. 
@hsanjuan Could you please prioritize this PR? Thanks in advance.
> api/rest: change *cid.Cid to cid.Cid in client iface

- .travis.yml
It seems branch = master prevents building snaps for tags (?)
License: MIT
> Fix: snaps for tags

- api/rest/client/client.go
Seems we forgot about this one.
License: MIT
> Fix IPFS() method missing in Client interface

- adder/adderutils/adderutils.go
- adder/ipfsadd/add.go
- adder/sharding/dag_service.go
- adder/sharding/dag_service_test.go
- api/add.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/client/request.go
- api/rest/restapi.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
This straigthens some mistakes with the outputs of the /add endpoints.
Currently, we had exactly the same output format which:
* was not exactly the ipfs API output format but was sort of similar
* made some weird concessions to be compatible (like having a string-type "size")
* was not aligned with Cluster API conventions (lowercase keys)
This corrects all this:
* The Cluster API /add output format now uses the right types and lowercase keys.
* `Hash` is now `Cid`, because the field carries a Cid.
* We copy error handling with request trailers from IPFS, and avoid carrying the
errors in the output objects.
* The proxy now returns exactly the types as ipfs would
* We add the X-Chunked-Output: 1 header, which is custom and redundant, but
otherwise breaks js-ipfs-api integrations with the …
> Add endpoints output: improvements and compliance

- snap/snapcraft.yaml
In the snap-installed distribution, calls like `ipfs-cluster-ctl add myfile.txt` fail with error `Error: open myfile.txt: permission denied` due to strict confinement to files in the /snap folder. Modifying confinement to `classic` will allow access to files elsewhere on the system.
> Allow ipfs-cluster-ctl to access files

- api/rest/config.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- config_test.go
By default, CORS headers allowing GET requests from everywhere are
set. This should facilitate the IPFS Web UI integration with the
Cluster API.
This commit refactors the sendResponse methods in the API, merging
them into one as it was difficult to follow the flows that actually
send something to the client. All tests now check the presence of
the configured headers too, to make sure no route was missed.
License: MIT
> Restapi: Add configurable response headers

- monitor/pubsubmon/pubsubmon.go
- monitor/pubsubmon/pubsubmon_test.go
> Pubsubmon: Gossipsub

- api/add.go
- api/rest/client/methods_test.go
When adding something that has a name with spaces, things fail
very badly :(
License: MIT
> Fix: escape the add query parameters correctly in the client

- .gitignore
- Makefile
- deptools/Makefile
This modifies the Makefile so that gx and gx-go downloads are first
attempted from the local ipfs gateway (127.0.0.1:8080) and then
from the offical gateway (ipfs.io).
Make and wget doesn't work well dealing with stuff in subfolders,
so I have moved deptools-related rules to the deptools folder in its own
Makefile.
#577 
License: MIT
> Fix #577: Try downloading gx and gx-go from local ipfs gateway first

- api/rest/client/client.go
- api/rest/client/methods.go
- api/rest/restapi.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
with metrics of type `<name>`
Fixes #449
> Issue #449 API endpoint for Peer Monitor metrics

- .travis.yml
- snap/snapcraft.yaml
Snaps won't publish with classic confimement or non-edge.
For the moment this works around that so that, at least,
there is releases on 'edge'  with strict confinement.
License: MIT
fyi @brianmcmichael . Will potentially re-enable `classic` if ever we're whitelisted.
> Fix publishing snaps

- api/rest/client/methods.go
- api/rest/client/request.go
- api/types.go
- cluster.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
- monitor/metrics/store.go
- monitor/metrics/util.go
- rpc_api.go
Issue #572 exposes metrics but they carry the peer ID in binary.
This was ok with our internal codecs but it doesn't seem to work
very well with json, and makes the output format unusable.
This makes the Metric.Peer field a string.
Additionally, fixes calling the command without arguments and displaying
the date in the right format.
License: MIT
> Make metrics human

- deptools/Makefile
> Update gx and gx-go to latest stable

- api/rest/config.go
- api/rest/config_test.go
@hsanjuan Can we get this one through as soon as possible? There is no good way to do this without installing `jq` on to a container and editing the `service.json` after `ipfs-cluster` has been initialised.
> add envcfg to rest api

- Dockerfile-test
- api/ipfsproxy/config.go
- api/ipfsproxy/config_test.go
- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- config/config.go
- config_test.go
- ipfscluster_test.go
Remove proxy_ and Proxy from proxy config objects without breaking
compatibility with previous revisions
Fixes #616
> Remove `proxy_` and `Proxy` from proxy config

- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- cluster.go
- cluster_test.go
- cmd/ipfs-cluster-service/main.go
- ipfscluster_test.go
- release.sh
- test/ipfs_mock.go
- version/version.go
This commit makes the proxy extract useful fixed headers (like CORS) from
the IPFS daemon API responses and then apply them to the responses
from hijacked endpoints like /add or /repo/stat.
It does this by caching a list of headers from the first IPFS API
response which has them. If we have not performed any proxied request or
managed to obtain the headers we're interested in, this will try triggering a
request to "/api/v0/version" to obtain them first.
This should fix the issues with using Cluster proxy with IPFS Companion and
Chrome.
License: MIT
> Fix #382: Extract headers from IPFS API requests and apply them to hijacked ones.

- api/rest/client/client.go
- api/rest/client/client_test.go
Before we resolved all /dns*/ multiaddresses before we used them.
When using HTTPs, the Go HTTP Client only sees the resolved IP address
and it is unable to negotiate TLS with a cerficate because the request
is not going to the hostname the certificate is signed for, but to
the IP. This leverages a recent feature in go-multiaddr-net
and uses directly the user-provided hostname.
> Fix ipfs-cluster-ctl with HTTPs multiaddresses

- adder/adderutils/adderutils.go
- api/add.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/restapi_test.go
- cmd/ipfs-cluster-ctl/main.go
Passing `?stream-channels=true` will keep the current behaviour. The `AddedOutput` objects are streamed to the client as they happen. `stream-channels=false` will, however, buffer all the addedOutput objects and return them as a final json array. Stream-related headers are adjusted accordingly.
The `stream-channels` is used because that's what ipfs uses (even though go-ipfs does not respect it).
The proxy /add will also acquire this feature.
Additionally, this modifies `ipfs-cluster-ctl add -Q` flag to apply as well when `--enc=json` is provided. This means that, in this case, only the last json-formatted `AddedOutput` object will be printed (before we ignored this flag in this case and printed everything). This should facilitate parsing the root hash result when using `ipfs-cluster-ctl` …
> Feat/632: support stream-channels query parameter when adding

- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
tl;dr: this solves the user's immediate need and, even if not tne strictest
solution, it is the simplest one.
I think we should not have the server buffer output when we can do it rather
easily client side and have the clients use their own memory for the task even
if `stream-channels=false` would do this.
We can always change the approach, but this is the minimal solution to
json array with all the AddedOutput things.
We might not buffer at all and hack a `[`, `,` separating elements and `]`
at the end, when json encoding is enabled, etc. But that would not be clean,
specially if we mean to support more output formats at some point.
Enabling supporting stream-channels=false in the api/rest/client means adding
new methods, with tests, modifying the interface etc etc. for what is …
> Fix #632: Add --no-stream to ipfs-cluster-ctl

- api/rest/config.go
- api/rest/config_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- package.json
- sharness/config/basic_auth/service.json
- sharness/config/ssl-basic_auth/service.json
- sharness/config/ssl/service.json
Maintenance.
Depends on #640 . Last commit only (trivial review).
> Sharness: update configuration files used in sharness

- api/rest/config.go
- api/rest/config_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- package.json
This adds support for handling preflight requests in the REST API
and fixes currently mostly broken CORS.
Before we just let the user add custom response headers to the
configuration "headers" key but this is not the best way because
CORs headers and requests need special handling and doing it wrong
has security implications.
Therefore, I have added specific CORS-related configuration options
which control CORS behavour. We are forced to change the "headers"
defaults and will notify the users about this in the changelog.
> Fix/639: Add support for handling preflight CORS requests

- config/config.go
- config/util.go
The JSON parsing of the config could error, but we skipped error checking and
use Validate() at the end. This caused that maybe some JSON parsing errors
where logged but the final error when validating the configuration came from
somewhere different, creating very confusing error messages for the user.
This changes this, along with removing hardcoded section lists. This also
removes a Sharder component section because, AFAIK, it was a left over
from the sharding branch and in the end there is no separate sharding
component that needs a config.
License: MIT
> config: Fix confusing errors

- sharness/t0032-ctl-health.sh
The ipfs container does not have `jq` in it. We need to run `jq` outside of it. This was logged when tests run, but the test did not fail.
> sharness: Fix test typo causing an empty grep

- ipfsconn/ipfshttp/ipfshttp.go
Every 10th pin the ipfs connector calls repo stat.
Because the call is async, the context was cancelled immediately and failed.
@lanzafame for 0.9.0
> Fix context cancelled too early.

- cmd/ipfs-cluster-service/configs.go
- observations/config.go
- observations/setup.go
This commit uses the Cluster.Peername to make the Jaeger
service name unique. This allows for inter-cluster traces
to show the relationship between the different peers in the
cluster. This commit also adds the Cluster.ID as a process
(global) tag on all spans produced by a peer. This is so
that a peer is uniquely identifiable, even when a more
human-friendly name has been used for the Cluster.Peername.
License: MIT
> make tracing service name unique

- api/ipfsproxy/config.go
- api/rest/client/client.go
- api/rest/config.go
- api/types.go
- cluster_config.go
- cluster_config_test.go
- config/config.go
- consensus/raft/raft.go
- ipfsconn/ipfshttp/config.go
The things removed here have been live for more than 2 releases.
License: MIT
> Remove backwards compatibility hacks

- Makefile
- sharness/t0030-ctl-pin.sh
We need to pre-create configuration folders and set write permissions
because https://github.com/ipfs/go-ipfs/pull/5048
License: MIT
> Fix docker-compose testing

- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- api/rest/client/methods_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- rpc_api.go
- state/mapstate/migrate.go
- test/rpc_api_mock.go
> ipfsproxy: use PinPath to match IPFS behaviour

- api/ipfsproxy/config.go
proxy: "extract_headers_path" and "extract_headers_ttl" should be
hidden options in the config
Fixes #698
> Hide `extract_headers_path`, `extract_headers_ttl`

- adder/ipfsadd/add.go
- adder/sharding/dag_service.go
- api/add.go
- api/ipfsproxy/ipfsproxy.go
- api/rest/restapi_test.go
- api/types_test.go
This was a leftover. For consisency, all CIDs coming out of the API
should have the canonical cid form ( { "/": "cid" } ), otherwise
we are inconsistent.
> Types: make AddedOutput carry a cid.Cid

- cmd/ipfs-cluster-ctl/main.go
This PR prevents a nil pointer panic, and attempts to make the offending code more clear.
Fixes #727
> fix nil pointer panic

- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
The problem is that addedOutputQuiet produced `{}` when converted to JSON.
> Fix: ctl: --enc=json shows empty output on "add"

- adder/adder.go
- api/add.go
- api/rest/client/methods.go
- cmd/ipfs-cluster-ctl/main.go
- go.mod
- go.sum
https://github.com/ipfs/go-ipfs/issues/6065 added URL support to the `add` command, along with `--nocopy` as well, replacing the need for the experimental `urlstore`. This PR proposes supporting `ipfs-cluster-ctl add --nocopy <url>`.
> support --nocopy when adding URLs

- api/types.go
> Fix #743: Use lowercase "version" in json version object

- api/rest/restapi.go
- api/rest/restapi_test.go
- api/types.go
Currently `curl -X GET http://localhost:9094/allocations` results in an
empty array, because no filter is provided. Solution to this would be
either 1) to consider filter as all if no filter is provided by the user
or 2) to make the `filter` parameter mandatory and reply with BadRequest
if no filter is provided
This commit makes the default filter as all
> Default allocations filter should be all

- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- rpc_api.go
- test/rpc_api_mock.go
The IPFS pin/update endpoint takes two arguments and usually
unpins the first and pins the second. It is a bit more efficient
to do it in a single operation than two separate ones.
This will make the proxy endpoint hijack pin/update requests.
First, the FROM pin is fetched from the state. If present, we
set the options (replication factors, actual allocations) from
that pin to the new one. Then we pin the TO item and proceed
to unpin the FROM item when `unpin` is not false.
We need to support path resolving, just like IPFS, therefore
it was necessary to expose IPFSResolve() via RPC.
Goes on top of #767 
Fixes #732
> Proxy: hijack pin/update

- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- api/rest/client/methods_test.go
- api/rest/restapi_test.go
- api/types.go
- api/types_test.go
- cluster.go
- cmd/ipfs-cluster-ctl/main.go
- ipfsconn/ipfshttp/ipfshttp.go
- rpc_api.go
- test/rpc_api_mock.go
It seems we forgot to convert this after peer.IDs became serializable. This
fixes it.
Also, inaugurating the new era of small PRs.
> Types: make UserAllocations []peer.ID instead of string

- adder/local/dag_service.go
- adder/local/dag_service_test.go
- adder/sharding/dag.go
- adder/sharding/dag_service_test.go
- adder/util.go
- api/ipfsproxy/ipfsproxy.go
- api/rest/restapi.go
- cluster.go
- connect_graph.go
- consensus/crdt/consensus.go
- consensus/raft/consensus.go
- consensus/raft/log_op.go
- informer/disk/disk.go
- informer/disk/disk_test.go
- informer/numpin/numpin.go
- informer/numpin/numpin_test.go
- ipfscluster.go
- pintracker/maptracker/maptracker.go
- pintracker/maptracker/maptracker_test.go
- pintracker/pintracker_test.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
- rpc_api.go
- test/rpc_api_mock.go
- test/test_test.go
I had thought of this for a very long time but there were no compelling
reasons to do it. Specifying RPC endpoint permissions becomes however
significantly nicer if each Component is a different RPC Service. This also
fixes some naming issues like having to prefix methods with the component name
to separate them from methods named in the same way in some other component
(Pin and IPFSPin).
Main changes here: in `rpc_api.go`. The rest is just renamings and adapting the tests.
> RPC: Give each component a different RPC Service

- cmd/ipfs-cluster-service/configs.go
- cmd/ipfs-cluster-service/lock.go
- cmd/ipfs-cluster-service/main.go
- config/identity.go
* Fix error messages (they must be in the form "doing something")
* Improve/reword some error messages
* Document the identity.json existance in the cli docs
* Fix a bunch of typos
* Fix missing folder path in the --help
* Fix cluster not locking when configuration is not there but folder is
* Fix force flag not overriding the config overwrite prompt
* Fix deletion of Raft state on re-init (not necessary if identity persists)
* Fix overwriting on identity (should not be overwritten if already exists)
Much of this paves the way to be able to run without service.json:
* Either taking default values (and using env vars) - maybe someday
* Either by getting a configuration template it from somewhere (ipfs, http)
at runtime - sooner.
> service: multiple fixes around init and identities

- cluster_config.go
- cluster_config_test.go
- clusterhost.go
- config_test.go
- go.mod
- go.sum
As follow up to #787, this uses the default libp2p connection manager for the
cluster libp2p host. The connection manager settings can be set in the main
configuration section (but it should be compatible with previous
configurations which have it unset).
This PR is just introducing the connection manager. Peer connection
protection etc will come in additional PRs.
> Feat: introduce a ConnectionManager for the libp2p host

- Makefile
- api/ipfsproxy/config.go
- api/rest/client/transports.go
- api/util.go
- cluster.go
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/state.go
- consensus/crdt/consensus.go
- peer_manager_test.go
- pstoremgr/pstoremgr.go
- pstoremgr/pstoremgr_test.go
- util.go
Fix #787: Connectivity fixes
Currently, unless doing Join() (--bootstrap), we do not connect to any peers on startup.
We however loaded up the peerstore file and Raft would automatically connect
older peers in its peerset to figure out who is the leader, catch up etc. DHT bootstrap, after Raft
was working, did the rest. This worked more or less well for Raft.
For CRDTs we need to connect to people on a normal boot as otherwise, unless
bootstrapping, this does not happen, even if the peerstore contains known peers.
This introduces a number of changes:
* Move peerstore file management back inside the Cluster component, which was
already in charge of saving the peerstore file.
* We keep saving all "known addresses" but we load them with a non permanent
TTL, so that there will be clean up of …
> Fix #787: Connectivity fixes

- api/types.go
Those regexes were compiled with each call to the function. As it's
called by PinLs, this resulted in a significant amount of memory used,
500MB in my case after a single call.
License: MIT
Signed-off-by: Michael Muré <batolettre@gmail.com>
> Fix: api: replace two regexes with strings.HasPrefix()

- config_test.go
- consensus/crdt/config.go
- consensus/crdt/config_test.go
- consensus/crdt/consensus.go
- ipfscluster_test.go
- peer_manager_test.go
Specifying "*" as part of "trusted_peers" in the configuration will
result in trusting all peers.
This is useful for private clusters where we don't want to list every
peer ID in the config.
> crdt: Allow to configure CRDT in "TrustAll" mode

- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- test/ipfs_mock.go
The switch to base32 as default output format for cidv1 keys in IPFS pin/ls
responses causes an error in PinLsCid as the base32 string does not correspond
to the base58 string expected by cluster when using an old peer.
This affects old Cluster peers running with new IPFS versions and new cluster
peers running with old IPFS versions for v1 CIDs.
Since Current master uses an updated cid dependency which also uses base32 by
default, master would already work with the latest IPFS daemon, so this is
just allowing to use cluster peers with older ipfs daemons, and preventing a
similar breakage in the future.
> Fix: default base32 in IPFS breaks cluster pin-ls

- consensus/raft/logging.go
- monitor/metrics/checker.go
- monitor/metrics/checker_test.go
- monitor/metrics/store.go
- monitor/metrics/store_test.go
Resolves #812.
This PR still requires clarification of whether the alerting for a peer should stop after one alert or several.
> alerting for peers stops after one alert

- consensus/raft/logging.go
- pstoremgr/pstoremgr.go
In this case we need to resolve (unlike with /dns4/), since otherwise
we may not know which peer ID the /dnsaddr is about.
> Fix importing peers using /dnsaddr/

- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- test/ipfs_mock.go
IPFSConnector Pin operation should not have a timeout since the start
of the operation, but a timeout since the last block was received,
thus only cancelling operations when there are no more blocks provided
in the network
Fixes #497
> Pin timeouts should start from the last block

- add_test.go
This test has been failing a lot lately. Waiting for metrics might help.
> Fix: fix flaky add test

- api/rest/config.go
- api/rest/config_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- informer/disk/config.go
- informer/disk/config_test.go
- informer/disk/disk.go
- informer/disk/disk_test.go
Went through all the `config.go` files. There was only one extra inconsistency that what was mentioned in the issue.
Fixes #778
> JSON Config object key should match JSON tags

- adder/local/dag_service.go
- adder/util.go
- api/ipfsproxy/ipfsproxy.go
- api/rest/client/client.go
- api/rest/client/lbclient.go
- api/rest/client/lbclient_test.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/restapi.go
- cluster.go
- cluster_test.go
- ipfscluster_test.go
- peer_manager_test.go
- rpc_api.go
- test/rpc_api_mock.go
These changes the following Cluster Go API methods:
* -> Cluster.Pin(ctx, cid, options) (pin, error)
* -> Cluster.Unpin(ctx, cid) (pin, error)
* -> Cluster.PinPath(ctx, path, opts) (pin,error)
Pin and Unpin now return the pinned object.
The signature of the methods now matches that of the API Client, is clearer as
to what options the user can set and is aligned with PinPath, UnpinPath, which
returned pin objects.
The REST API now returns the Pinned/Unpinned object rather than 204-Accepted.
This was necessary for a cleaner pin/update approach, which I'm working on in
another branch.
Most of the changes here are updating tests to the new signatures
> Improve pin/unpin method signatures

- cluster.go
- cmd/ipfs-cluster-service/main.go
- config/config.go
- consensus/crdt/config.go
- pstoremgr/pstoremgr.go
- pstoremgr/pstoremgr_test.go
- sharness/t0021-service-init.sh
This commit adds `--peers` option to `ipfs-cluster-service init`
`ipfs-cluster-service init --peers <multiaddress,multiaddress>`
- Adds and writes the given peers to the peerstore file
- For raft config section, adds the peer IDs to the `init_peerset`
- For crdt config section, add the peer IDs to the `trusted_peers`
> Init should take a list of peers

- consensus/raft/raft.go
- pstoremgr/pstoremgr.go
With this PR, cluster peer will observe on events of peer removal
from cluster. On occurence of the event, the cluster peer will clear
the removed peer from its peerstore.
Fixes #840
> When a peer is removed, clear it from peerstore 

- api/rest/config_test.go
- api/rest/restapi.go
Cancelling its context before closing the listeners and de-registering
protocols is ground for panics on libp2p.
#853
> Fix #853: Make a more orderly shutdown of rest api libp2p host

- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/main.go
Add bootstrap peers to list of trusted peers for crdt.
Just adding them to crdt trusted_peers in config is enough.
Fixes #834
> Auto-trust bootstrap peers

- api/rest/restapi.go
- api/rest/restapi_test.go
- test/cids.go
- test/rpc_api_mock.go
With this commit
- If cid in `DELETE /pins/{cid}` isn't part of the pinset, it would
return 404
- If path in `DELETE /pins/{keyType}/{path}` resolves to a cid that
isn't part of the pinset, it would return 404
Fixes #742
> 404 on deleting a pin that isn't part of pinset

- ipfsconn/ipfshttp/config.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
As raised in #793, sometimes the user wants to simply disallow unpinning
altogether in a Cluster peer so that no content can be removed from IPFS
through cluster, even when crendentials are compromised (including access to
RPC endpoint).
This introduces a disable_unpinning parameter for the ipfshttp
connector. There is no way that a cluster will effecitvely unpin something if
the connector refuses to ask ipfs.
> Fix #793: Allow to fully disable unpinning

- Dockerfile
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/main.go
- docker-compose.yml
- docker/cluster-restart.sh
- sharness/lib/test-lib.sh
- sharness/t0052-service-state-export.sh
- sharness/t0053-service-state-import.sh
- sharness/t0054-service-state-clean.sh
It has a few implications to launch a raft peer when you wanted to do crdt and vice-versa.
Same when exporting and exporting states.
Users starting cluster peers should be explicit about their consensus choice.
Also, if we ever want to make `crdt` the default, we can't do that before
making `raft` non-default first. I don't like to break things but otherwise
the experience for new users wanting to try crdts might be aweful.
> service: Make --consensus a mandatory flag

- go.mod
- go.sum
Fix in libp2p-peerstore arrived.
#648
> Fix #648: Update go-libp2p-peerstore with ttl fixes

- sharness/t0021-service-init.sh
[AddrInfosFromP2pAddrs](https://github.com/libp2p/go-libp2p-core/blob/master/peer/addrinfo.go#L25)
might not keep order therefore the tests flip.
> Fix sharness init with --peers test

- cluster.go
- cluster_config.go
- ipfscluster_test.go
- rpc_api.go
Peers configured with follower_mode = true fail to add/pin/unpin.
Additionally they do not contact other peers when doing Status, Sync or
Recover and report on themselves.
They still contact other peers when doing "peers ls", as this is an OpenRPC
endpoint.
This is merely improving user interaction with a cluster peer and avoids
getting into confusing places:
* pin/unpin seems to work even no one trusts them
* status will query all peers in the peerset only to get auth errors and
ignore them, becoming way slower than it could be
This is not a security feature.
#803
> Fix #803: Add "follower_mode" to the config

- Dockerfile
- Dockerfile-test
This should improve the amount of CI errors lately when hitting github.
> Dockerfiles: enable goproxy

- cmd/ipfs-cluster-ctl/main.go
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/main.go
Because string slice is not very user friendly. Using string instead
would allow us to pass a comma separated list of arguments in one option
Fixes #841
> Use string flag instead of string slice

- Dockerfile
- Dockerfile-test
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/lock.go
- cmd/ipfs-cluster-service/main.go
- cmdutils/configs.go
- cmdutils/state.go
- config/config.go
- docker-compose.yml
- docker/cluster-restart.sh
- sharness/lib/test-lib.sh
- sharness/run-sharness-tests.sh
- sharness/t0021-service-init.sh
- sharness/t0052-service-state-export.sh
- sharness/t0053-service-state-import.sh
- sharness/t0054-service-state-clean.sh
Fixes #865.
This makes the necessary changes so that consensu is selected on "init" with a
flag set, by default, to "crdt". This generates only a "crdt" or a "raft"
section, not both.
If the configuration file has a "raft" section, "raft" will be used to start
the daemon. If it has a "crdt" section, "crdt" will be used. If it has none or
both sections, an error will happen.
This also affects "state *" commands, which will now autoselect how to work
from the existing configuration.
> Service: Select consensus on "init" (not on "daemon")

- config_test.go
- ipfsconn/ipfshttp/config.go
- ipfsconn/ipfshttp/config_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- sharness/config/basic_auth/service.json
- sharness/config/ssl-basic_auth/service.json
- sharness/config/ssl/service.json
- test/ipfs_mock.go
go-ipfs no longer performs a global lock when two simultaneous requests to pin happen. This allows us to remove a bunch of code.
Made on top of #869 , will re-push once merged.
> ipfshttp: Remove "refs" method

- add_test.go
- adder/adder_test.go
- adder/local/dag_service.go
- adder/sharding/dag.go
- adder/sharding/dag_service.go
- adder/sharding/shard.go
- adder/util.go
- api/types.go
- test/rpc_api_mock.go
- test/sharding.go
With this commit
- We don't stop adding if one peer failed. We keep adding to peers that
never errored
- We remember peers(only till current `/add` request) that errored and
don't try to put more block them
TODO: Tests
Fixes #852
> Improve error handling on `add`

- Dockerfile
- Dockerfile-bundle
- Dockerfile-test
- Makefile
- clusterhost.go
- cmd/ipfs-cluster-service/daemon.go
- docker-compose.yml
- docker/entrypoint.sh
- docker/start-daemons.sh
- docker/test-entrypoint.sh
- go.sum
- peer_manager_test.go
cluster: add mDNS service discovery
I always thought the libp2p node would do this, but it is not the case.
With this, CRDT peers are able to autodiscover on local networks.
More commits coming.
> Improve Docker support for CRDTs

- cluster.go
- cluster_config.go
- clusterhost.go
- cmd/ipfs-cluster-service/daemon.go
- config_test.go
- peer_manager_test.go
- pstoremgr/pstoremgr.go
Setting up mDNS outside the Cluster is dirtier and allows less configuration.
This adds MDNSInterval to the cluster config options and allow disabling it
when the option is set to 0.
> mDNS: attach mDNS inside the Cluster. Allow interval configuration.

- consensus/crdt/config.go
- consensus/crdt/config_test.go
:/ good that I added a warning
> Fix: trust-all remained enabled always

- api/rest/client/client.go
- api/rest/client/client_test.go
- api/rest/restapi.go
- api/types.go
- api/types_test.go
- api/util.go
- cluster.go
- cmd/ipfs-cluster-ctl/main.go
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/main.go
- consensus/raft/consensus.go
- peer_manager_test.go
- pstoremgr/pstoremgr.go
- pstoremgr/pstoremgr_test.go
- sharness/t0021-service-init.sh
- test/rpc_api_mock.go
> Use `p2p` protocol name over `ipfs` for multiaddr

- cluster.go
- pintracker/maptracker/config.go
- pintracker/maptracker/maptracker.go
- abort if a Track() calls fails due to queue being full
- increase max pin queue size to 1 million
- hind max_pin_queue_size from configuration
- use an elaborated error message
Fixes #377
> Error queue is full

- Makefile
- sharness/lib/test-lib.sh
Last tag was made on v1.1.0 (2018-09-30), so I have used latest commit instead.
Fixes #797
> Use the updated sharness library

- api/types.go
- cluster.go
- ipfscluster_test.go
- peer_manager_test.go
* pin() should not allocate if allocations are already provided
* pin() should not skip pinning if the exact same pin exists
* Additionally this was unreliable as it allocated it before
so the pin may have existed but the allocations may have been
artificially changed.
* pin() re-uses existing pin when pin options are the same and thus
avoids changing the allocations of a pin.
As a side effect, this fixes re-allocations which were broken: peers
called `shouldPeerRepinCid()` and instead of repinning that single
cid proceeded to repin the full state. For every pin.
Additionally tests have been adapted. It may be that some re-alloc tests
were very unreliable for the problems above.
> Fix: handling allocations

- cmd/ipfs-cluster-ctl/main.go
- go.mod
Fixes #755
> Might get away with it by making it a string flag and parsing the values...
this would work, but still we would have to explain the value 0 replication factor for someone who passes `-r "0"`
So I have avoided changing the flag
> Explanation of 0 replication factor

- monitor/metrics/checker.go
- monitor/pubsubmon/pubsubmon_test.go
Fixes #410 
> The problem is: if a peer is removed from the peerset (from the cluster), the Store will still keep a key containing the metrics.Window for that peer, as this is never cleaned up.
metrics.Window gets cleaned up already https://github.com/ipfs/ipfs-cluster/issues/410#issuecomment-523044477
We can use PeersFunc to get the peerset, which we can get from consensus.Peers
- Raft has information about the peers, but you would not expect many coming and going peers in raft, so there isn't really a point doing this.
- CRDT uses metrics for consensus.Peers, so no new information there
So for both of crdt and raft we can use this way:
if peer metrics fail for a threshold time, consider that peer to be not part of peer set and remove metrics. 
This PR just adds a test to check that …
> Test that expired PeerMetrics gets deleted

- pintracker/maptracker/maptracker.go
- pintracker/stateless/config.go
- pintracker/stateless/stateless.go
- pintracker/util/pin.go
- increase max pin queue size to 1 million
- hide max_pin_queue_size from configuration
same as https://github.com/ipfs/ipfs-cluster/pull/901/ , but for stateless pintracker
Fixes #377
> Error queue is full for stateless pintracker

- Dockerfile
- Dockerfile-bundle
- Dockerfile-test
- Makefile
- cmd/ipfs-cluster-ctl/Makefile
- cmd/ipfs-cluster-service/Makefile
- go.mod
This should speed up Dockerfile builds, particularly when building after
updating the code since the modules will not be to be re-downloaded.
> Dockerfiles: download modules in advance

- api/types.go
- cmd/ipfs-cluster-ctl/graph.go
- cmd/ipfs-cluster-ctl/graph_test.go
- connect_graph.go
- go.mod
- go.sum
- ipfscluster_test.go
- Distinguish between trusted nodes (dark green) and untrusted nodes
(light green)
- Distinguish between Cluster nodes (filled) and IPFS nodes (hollow)
- Straight edge between Cluster node and it's corresponding IPFS node
- Cluster nodes always on top row, IPFS nodes always on bottom row
- Shorter labels for nodes
Fixes #800
> Improve connection graph output

- go.mod
- go.sum
Fixes #936 
Fixing
```
go: github.com/btcsuite/btcd@v0.20.0-beta: reading https://proxy.golang.org/github.com/btcsuite/btcd/@v/v0.20.0-beta.mod: 410 Gone
```
> Bump btcd to v0.20.1-beta

- cluster.go
- cluster_config.go
- cluster_config_test.go
This adds a PeerAddresses entry to the main cluster configuration.
The peer will ingest and potentially connect to those peer addresses during
the start (similarly to the ones in the peerstore).
This allows to provide "bootstrap" (as in "peers we connect to") addresses
directly in the configuration, which is useful when distributing a single
configuration template that will allow a cluster peer to know where to connect
on the first boot.
> config: Add PeerAddresses

- allocate.go
- cluster.go
- cluster_test.go
- cmd/ipfs-cluster-service/daemon.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- rpc_api.go
- rpc_policy.go
- Cluster accepts multiple informer components
- function that expects only one informer component, will use a informer
which has name same as `Cluster.preferredMetric`
- Added rpc api for send all informer metrics
Fixes #940
> Allow and run multiple informer components

- observations/setup.go
On using `/debug/pprof` as index endpoint, profiles contained by it
would point to wrong url. For example, link for `allocs` would be
`/debug/allocs` (results in 404), whereas it should actually be
`/debug/pprof/allocs`.
Use a trailing slash to get correct links. `/debug/pprof` will
automatically be redirected to `/debug/pprof/`
> Use index endpoint with a trailing slash

- config/config.go
* Allow detection of source-download errors by adding IsSourceDownloadError method.
* Treat non-success response codes as a failure to fetch the source.
* Set the Source url before errors happens so it can be consulted even in that case.
> config manager: Improve source-fetch error handling

- cluster.go
- cluster_config.go
- config_test.go
- pintracker/pintracker_test.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
- test/rpc_api_mock.go
StateSync() used to take care of this by issuing Track() calls. But this
functionality was removed.
This starts returning items that are in the state but not on IPFS as
PIN_ERRORs. It ensures that the Recover methods see them so that they can
trigger repinnings for missing items. This covers cases where the user
modifies the ipfs state manually, or resets the ipfs daemon but keeps the
cluster state, and cases where cluster was stopped half-way through a pinning.
>  Fix: stateless: cluster should pin items that are in the state but not on ipfs

- cmd/ipfs-cluster-service/main.go
- logging.go
- Example: export LOG_FACS="cluster:debug,raft:debug"
`kelseyhightower/envconfig` works only with structs. I will look at this again and see if there a way to do this like `export LOG_CLUSTER=debug`
#938
> Environment variable to set loglevels for individual identifiers

- cluster_config.go
User should see this is an array.
> cluster config: initialize peer addresses to [] rather than null.

- cmd/ipfs-cluster-ctl/Makefile
- cmd/ipfs-cluster-follow/Makefile
- cmd/ipfs-cluster-service/Makefile
This results in more reproduceable builds.
Additionally, sources command to list all go-files and not just those
one directory below.
> Fix #1012: Trim paths on Makefile builds

- adder/util.go
- api/types.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- test/cids.go
- test/ipfs_mock.go
Currently we were only specifying the block format. When adding with
a custom hash function, even though we produced the right cids, IPFS
did not know the hash function and ended up storing them using SHA256.
Additionally, since NodeWithMeta serializes the CID, we do not need
to carry a Format parameter (which specifies the Codec): it is already
embedded.
Tests have been added and BlockPut in ipfshttp now checks that the
response's CID matches the data sent. This will catch errors like
what was happening, but also any data corruption between cluster and
IPFS during the block upload.
> Adder: fix #1006: Specify block format, hash and length when adding

- datastore/badger/config.go
They are the same that go-ipfs has started using, our users can
always overwrite them though (unlike go-ipfs).
> badger: reduce memory footprint with better default options

- cluster.go
- ipfscluster_test.go
Running `$ go test `in ipfs-cluster repo shows the following error:
```
23:39:46.480 ERROR     engine: datastore closed engine.go:291
23:39:46.481 ERROR     engine: datastore closed engine.go:291
```
Am I missing a step ?
> Fixes #996 pin expiry is updated if set in options

- adder/sharding/dag_service.go
- adder/single/dag_service.go
- allocate.go
- api/add.go
- api/ipfsproxy/ipfsproxy.go
- api/pb/types.proto
- api/types.go
- cluster.go
- cluster_test.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
- go.mod
- go.sum
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
- rpc_api.go
- sharness/t0030-ctl-pin.sh
- test/ipfs_mock.go
- test/rpc_api_mock.go
This exposes pinning modes (direct/recursive) with a new `mode` API parameter and a new flag in pin/add.
Implementation-wise, this is a new PinOption, which is made to match the MaxDepth field when creating the Pin object. Since Max Depth is already stored we do not need to change the disk serialization.
Additionally some improvements have been added around pinning and unpinning, for speed and resilience.
> Fix #1009: support pinning in direct mode

- version/version.go
The RPC endpoints no longer change much, but every minor release enforces that
all peers in a Cluster must run on the same version.
This was meant to allow greater flexibility when upgrading the RPC
endpoints. Now we should not be in a situation that releasing a minor cluster
version causes peers incompatibilities, even though nothing changes on the RPC
side of things.
Therefore we make 0.12 the RPC protocol version going forward and detach it
from the actual cluster version from this point.
> Set the RPC Protocol Version to a fixed value

- cmd/ipfs-cluster-ctl/main.go
Fixes #1184 
Changes: 
- Adds name and expire-in flags to the pin update command in ipfs-cluster-ctl.
- Updates PinOptions used
[PinUpdate](https://github.com/ipfs/ipfs-cluster/blob/d2a83e45f1ad5f84a3eae70b46fb9b521b90ab03/cluster.go#L1498) handles changes in name and expire
> Fix #1184: Pin update options (name, expire) in ipfs-cluster-ctl

- api/rest/client/client.go
- cmd/ipfs-cluster-ctl/main.go
#1222 
Changes:
- adds methods to create client configs from a dnsaddr host input
- uses the LBClient in ipfs-cluster-ctl
> Feat #1222: Integrates the failover client in ipfs-cluster-ctl

- Dockerfile
- Dockerfile-test
#1085 
Changes: 
- Downloads appropriate tini binary based on the machine architecture https://github.com/ipfs/go-ipfs/pull/7187
- Builds a static su-exec binary to make it robust (no dependency on libraries) and cross-platform support https://github.com/ipfs/go-ipfs/pull/7505
For uploading images with different machine architectures to DockerHub, [Buildx](https://docs.docker.com/buildx/working-with-buildx/) or some other tool may be required
Any suggestions on how to test this for architectures other than amd64? 
Other libraries required would have to be imported as shown here  https://github.com/ipfs/go-ipfs/pull/6854
> Feat 1085: Dockerfile to support multiple architectures

- api/ipfsproxy/ipfsproxy.go
- api/pb/types.pb.go
Fixes #1286. Some AddedOutput objects carry an undefined CID. This was getting
stringified as 'b', making the proxy responses include this rather than
skipping setting the field.
> ipfsproxy: fix 'undefined cid' string appeareance in progress output

- cluster_config.go
- consensus/crdt/config.go
- consensus/crdt/consensus.go
Currently, it was not looking at the signer of the message, but at the
peer that relayed it, to verify the validity of the message.
This caused that under certain gossip graph configurations, some nodes would only
get messages via untrusted peers, and thus be unable to sync the chain.
> Fix pubsub validation check

- cmd/ipfs-cluster-ctl/main.go
A "simplest thing that could work" implementation of adding a `--wait` flag to the ipfs-cluster-ctl add command. Allows CI to wait for cluster to fully replicate the files just added before continuting, or fail if replication fails.
A dull thing with this change is that `add -w` is already used as the alias for `add --wrap-with-directory`, so the meaning of `-w` is inconsistent between the `add` and `pin` commands. It seemed unwise to change the existing meaning of `add -w` so I have not updated it here.
Fixes #1285
License: MIT
Signed-off-by: Oli Evans <oli@tableflip.io>
> feat: add --wait flag to ipfs-cluster-ctl add

- cluster.go
- if discovery.NewMdnsService errors on start, show warning "error message, MDNS service will be disabled"
- same as setting MDNSInterval to 0: NewCluster is still created and daemon runs, but without MDNS
closes #1193 
needs review
branch was checked out from `v0.13.1`
`make test` [pass](https://github.com/sergeiudris/ipfs-lab/issues/4#issuecomment-778145792)
`make test_sharness` [returns same output ](https://github.com/sergeiudris/ipfs-lab/issues/4#issuecomment-778147032) with/without changes
> feat: make MDNS failure on start non-fatal

- go.mod
- go.sum
- monitor/pubsubmon/pubsubmon.go
go-multicodec has been deprecated and it was just a wrapper.
This switches directly to ugorji/go/codec's msgpack for cluster metrics
serialization.
> monitor: remove dependency to go-multicodec

- api/rest/client/transports.go
- api/rest/restapi.go
- go.mod
Instead they should use noise, and fallback to tls.
This should not break compatibility with previous versions as both old and new
are able to speak tls.
Fixes #1315
> Restapi: API libp2p host and client should no longer use secio.

- go.mod
- go.sum
- monitor/pubsubmon/pubsubmon.go
This reverts commit fab2ed814934a19b690bc402a7b499c99f661cfd.
It turns out that messages are serialized with a multicodec header prefix and removing this breaks metric broadcasts between older and newer peers, something we don't want to do until we have a properly breaking upgrade.
> Revert "monitor: remove dependency to go-multicodec (#1313)"

- api/types.go
- cluster.go
- cmd/ipfs-cluster-ctl/formatters.go
The Allocations of a pin that has been added with default replication factor
are kept even when the replication factor turns out to be -1.
This resulted in the Status(cid) code skipping calls to a number of peers
and setting the pin directly as REMOTE.
The fix, on one side makes sure Allocations is always nil when the replication
factor is -1. On the other size, lets the globalPinInfoCid method check the
replication factor value, rather than the number of allocations to decide if
any nodes are bound to be remote.
On the plus side, the pin tracker used the IsRemotePin method, which uses the
replication factor, so things were pinned even if the Status(cid) method shows
them as remote.
#1319
> Fixes #1319: Status wrongly shows pins as REMOTE

- adder/adder.go
- adder/adder_test.go
- adder/sharding/dag.go
- adder/sharding/dag_service_test.go
- api/add.go
- api/rest/client/methods_test.go
- cmd/ipfs-cluster-ctl/main.go
- go.mod
- go.sum
- sharness/t0031-ctl-add.sh
- test/sharding.go
This commit adds a new add option: "format".
This option specifies how IPFS Cluster is expected to build the DAG when
adding content. By default, it takes a "unixfs", which chunks and DAG-ifies as
it did before, resulting in a UnixFSv1 DAG.
Alternatively, it can be set to "car". In this case, Cluster will directly
read blocks from the CAR file and add them.
Adding CAR files or doing normal processing is independent from letting
cluster do sharding or not. If sharding is ever enabled, Cluster could
potentially shard a large CAR file among peers.
Currently, importing CAR files is limited to a single CAR file with a single
root (the one that is pinned). Future iterations may support multiple CARs
and/or multiple roots by transparently wrapping them.
> Feat: support adding CAR files

- consensus/crdt/config.go
- consensus/crdt/config_test.go
- consensus/crdt/consensus.go
- consensus/crdt/consensus_test.go
This adds batching support to crdt-consensus per #1008 . The crdt component can now take
advantage of the BatchingState, which uses the batching-crdt datastore. In
batching mode, the crdt datastore groups any Add and Delete operations
in a single delta (instead of just 1, as it does by default).
Batching is enabled in the crdt configuration section by setting MaxBatchSize
**and** MaxBatchAge. These two settings control when a batch is committed,
either by reaching a maximum number of pin/unpin operations, or by reaching a
maximum age.
Batching unlocks large pin-ingestion scalability for clusters, but should be
set according to expected work loads. An additional, hidden MaxQueueSize
parameter provides the ability to perform backpressure on Pin/Unpin
requests. When more than MaxQueueSize …
> crdt: Add batching support

- cluster.go
- cluster_config.go
- clusterhost.go
- pstoremgr/pstoremgr.go
This PR improves some timeout behaviours.
It introduces an option to control the dial timeout and sets 15 second deadlines for broadcast calls triggered by Peers() and StatusCID(), which should be relatively fast.
> Better timeouts

- api/add.go
- api/add_test.go
Fixes #1358. Mimics go-ipfs defaults.
> Fix #1358: Set RawLeaves to true when unset and CidVersion=1

- docker-compose.yml
The [quick start guide](https://cluster.ipfs.io/documentation/quickstart/) references this file, which ends up using older `go-ipfs` 0.4.23.
The `release` tag seems to not be used anymore, and `latest` seems the correct one to use here per https://hub.docker.com/r/ipfs/go-ipfs/tags?page=1&ordering=last_updated&name=latest
> chore: use latest go ipfs in docker compose

- .travis.yml
- cluster_test.go
- clusterhost.go
- cmd/ipfs-cluster-follow/commands.go
- cmd/ipfs-cluster-service/daemon.go
- cmd/ipfs-cluster-service/lock.go
- cmd/ipfs-cluster-service/main.go
- cmdutils/configs.go
- cmdutils/state.go
- config_test.go
- datastore/badger/config_test.go
- datastore/leveldb/config.go
- datastore/leveldb/config_test.go
- datastore/leveldb/leveldb.go
- go.mod
- ipfscluster_test.go
Badger can take 1000x the amount of needed space if not GC'ed or compacted
(#1320), even for non heavy usage. Cluster has no provisions to run datastore
GC operations and while they could be added, they are not ensured to
help. Improvements on Badger v3 might help but would still need to GC
explicitally.
Cluster was however designed to support any go-datastore as backend.
This commit adds LevelDB support. LevelDB go-datastore wrapper is mature, does
not need GC and should work well for most cluster usecases, which are not
overly demanding.
A new `--datastore` flag has been added on init. The store backend is selected
based on the value in the configuration, similar to how raft/crdt is. The
default is set to leveldb. From now on it should be easier to add additional
backends, i.e. …
> Support a levelDB backend for cluster

- config/util.go
- config_test.go
- datastore/badger/badger.go
- datastore/badger/config.go
- datastore/badger/config_test.go
- go.mod
- go.sum
This takes advantage of go-ds-badger "auto-gc" feature.
It will run a GC cycle made of multiple GC rounds (until it cannot GC more)
automatically. The behaviour is enabled by default in the configuration and
can be disabled by setting "gc_interval" to "0m". Hopefully this prevents
badger datastores from growing crazy.
> Fix #1320: Add automatic GC to Badger datastore

- api/rest/restapi.go
- api/types.go
- cluster.go
- ipfscluster.go
- ipfscluster_test.go
- pintracker/pintracker_test.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
- rpc_api.go
- test/rpc_api_mock.go
This commit modifies the pintracker StatusAll call to take a status filter.
This allows to skip a PinLs call to ipfs when checking status for items that
are queued, pinning, unpinning or in error. Those status come directly from
the operation tracker. This should result in a significant performance
increase for those calls, particularly in nodes with several hundred thousand
pins and more, where the call to IPFS is very expensive.
A new TrackerStatusUnexpectedlyUnpinned status has been introduce to
differentiate between pin errors (tracked by the operation tracker) and "lost"
items (which before were pin errors too). This new status is handled by the
Recover() operation as before.
Fixes #1360 .
> Fix #1360: Efficient pinset status with filters

- ipfscluster_test.go
This resulted in too-many-files-open when running with leveldb.
> Fix: tests: close datastore on cluster node shutdown.

- cmd/ipfs-cluster-ctl/main.go
When using SSL and not talking to libp2p-http endpoints, we should not
resolve the dns names in the multiaddresses as otherwise we cannot
verify the https certificates used by the remote endpoint.
Fixes #1403.
> Fix #1403: ctl: ssl errors when talking to https remote peers

- api/rest/restapi.go
- cmd/ipfs-cluster-ctl/main.go
The restapi component supports filters for the pinset. This was done to keep
expected output when sharding was fully supported by filtering out "internal"
pins.
However this filter requires looping on the full pinset and re-allocating  and
usually does nothing. The useless copy is significant for really big pinsets.
Additionally, ipfs-cluster-ctl set the filter by default to "pins". By setting
it to "all" instead we can skip the whole filtering step and, in practice, get the
same results.
> restapi: allocationsHandler: skip filtering pins when not needed.

- cmd/ipfs-cluster-follow/commands.go
- cmd/ipfs-cluster-service/main.go
- logging.go
We have default log levels for things like swarm and go-rpc but we were ignoring them. Among the effects, the go-rpc library pollutes logs a lot with things like "context timeout" and 0 useful information. These errors will be logged by other components when relevant.
> Fix: improve log level handling

- api/rest/restapi.go
The Gorilla muxer StrictSlash option uses a 301 permanent redirect, which
results in POST requests becoming GET requests in most clients.  Thus we use
our own middleware that performs a 307 redirect.  See issue #1415 for more
details.
Fixes #1415
> restapi: fix #1415: paths ending in / get 307-redirect instead of 301

- api/types.go
- cmd/ipfs-cluster-ctl/formatters.go
- pintracker/optracker/operation.go
- pintracker/optracker/operationtracker.go
- pintracker/stateless/config.go
- pintracker/stateless/config_test.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
Fixes #1469 
This PR improves the stateless pintracker component in multiple ways:
* The operation manager tracks retry counts for operations. These are shown as part of the pin status. Retry counts are not stored on disk. They are reset on restart.
* The pinning queue is doubled into a priority queue and a normal queue. Items on the priority queue get to be processed first.
* The pintracker decides which pins end up in the priority queue based on two configurations settings:
* The number of retries that a pin has on it.
* The age of the pin.
In practical terms: a cluster may ingest many thousands of pins, not all of which end up pinned (low quality providers etc). Those that fail to pin multiple times (retries) or potentially become old (i.e. they were added more than a day ago and are …
> Pintracker: support prioritary pinning for recent pins with small number of retries

- CHANGELOG.md
- cmd/ipfs-cluster-ctl/formatters.go
Make sure we print the value in all cases. Use the weight for the free-space
metric, no need to parse the value anymore.
> ipfs-cluster-ctl: improve printing of health metrics

- api/types.go
- api/types_test.go
- ipfsconn/ipfshttp/ipfshttp_test.go
The pin objects now include an Origin field which was set to
multiaddr.Multiaddr.
This type is an interface and has no idea how to deserialize itself. As a
result, an state json export cannot be deseralized.
We had already added a wrapper Multiaddr type to handle these issues. I
believe this fix does not affect anything else other than fixing
UnmarshalJSON. PB types are deserialized by hand and it should not make a
difference.
> Fix state deserialization

- api/common/api.go
- api/rest/client/request.go
- go.mod
- go.sum
- pintracker/stateless/stateless.go
- state/dsstate/datastore.go
- Upgrades go-ds-crdt with a 3x performance improvement when doing a List. Current benchmark is 11k->36k pins per second listed.
- Adds logging when a List operation is ongoing and has more than 500k items (starts taking time). This can inform the user about the aliveness of the operation and total number of pins before they are actually delivered. It is very useful to be mindful of overly short recover-interval settings etc. It takes several minutes to list a state with 10M items now.
- Fixes a shutdown issue in the pintracker.
> Performance improvements to state List() and other minor things

- cluster.go
Invalid metrics returned by informers should not be sent around
> Avoid publishing invalid metrics

- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
This must has been an oversight. We added a special unexpectedly_unpinned
status so that we could just return things from the operation tracker when
filtering by pin_error. unexpectedly_unpinned are things that we have no
operation for but are unpinned on ipfs.
Status however still returned a pin_error state for these, even though,
StatusAll would not show them when filtering with pin_error, and would show
them as unexpectedly_unpinned otherwise.
Since Recover correctly repins pin_error and unexpectedly_unpinned, this
change has no further consequences.
> pintracker: set status unexpectedly_unpinned correctly on Status()

- cluster.go
- cluster_test.go
- ipfscluster.go
- ipfscluster_test.go
- pintracker/pintracker_test.go
- pintracker/stateless/stateless.go
We call RecoverAll regularly and I noticed it was way slower than it should be.
After all, it should just loop the pinset and enqueued items that are
unexpectedly unpinned or in pin error.
However, at some point we decided that RecoverAll would return information for
all pins, regardless of whether they were recovered or not. This ends up
resulting in a separate Status call for every pin that is already pinned, and
this call hits IPFS. This is pretty bad with big pinsets.
This commit fixes that, we return no state information for pins that are not
touched.
> pintracker: RecoverAll should only return status for recovered items

- config_test.go
- ipfsconn/ipfshttp/config.go
- ipfsconn/ipfshttp/config_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- rpc_api.go
Given that every pin and block/put writes something to IPFS and thus increases
the repo size, a while ago we added a check to let the IPFS connector directly
trigger the sending of metrics every 10 of such requests. This was meant to
update the metrics more often so that balancing happened more granularly
(particularly the freespace one).
In practice, on a cluster that receives several hundreds of pin/adds
operations in a few seconds, this is just bad.
So:
* We disable by default the whole thing.
* We add a new InformerTriggerInterval configuration option to enable the thing.
* Fix a bug that made this always call the first informer, which may not
have been the freespace one).
> Fix: repo/stat gets hammered on busy cluster peers

- cluster.go
In happens when no tags are defined and I thought it was fixed.
> Remove warning message about informer metrics

- consensus/crdt/config.go
- consensus/crdt/config_test.go
- consensus/crdt/consensus.go
- go.mod
- go.sum
The new version supports auto-repair of the datastore.
This adds a new `repair_interval` option in the crdt configuration.
Peers that upgrade will have it unset, which means 0, which disables repairs.
New peers will generate configurations with a default of 1 hour.
Fixes #1007
> Update go-ds-crdt and add RepairInterval option

- api/rest/client/methods_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- api/types.go
- cluster.go
- test/rpc_api_mock.go
This allows to specifically request status for several CIDs as
provided in the "cids" query parameter, instead of request status for
all CIDs.
In this case, the filter is ignored.
> Restapi: add "cids" query param to /pins

- adder/adder.go
- adder/adderutils/adderutils.go
- adder/sharding/dag_service.go
- adder/sharding/dag_service_test.go
- adder/single/dag_service.go
- adder/single/dag_service_test.go
- api/add.go
- api/rest/client/client.go
- api/rest/client/lbclient.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- cluster.go
- rpc_api.go
This does 3 things:
- Add a NoPin option to the adder. When set to true, the adding process does not
send a pin in the end.
- When user-allocations are set and local=true happens, we do not overwrite
the allocations returned by the allocator to include the local peer
anymore, as this could alter user-allocations.
- Some code improvement (remove pointers).
> Adder: Add "no-pin" option.

- allocate.go
- cluster_config.go
- cluster_config_test.go
- config_test.go
Adds pin_only_on_cluster_peers configuration option
Fixes #1585 .
> allocator: Filter out metrics from non-trusted peers when configured

- api/rest/client/client.go
- api/rest/client/lbclient.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- cmd/ipfs-cluster-ctl/main.go
Adds support for this in the Go RESTAPI client and the ipfs-cluster-ctl command.
Fixes #1564 .
> Support querying status for multiple CIDs in clients

- adder/adder.go
- adder/adder_test.go
- adder/ipfsadd/add.go
- adder/sharding/dag_service.go
- adder/sharding/shard.go
- adder/single/dag_service.go
- api/add.go
This adds a new allocations field to add response objects which
provides the cluster peers to which the content has been allocated.
In the case of sharded dags, it provides peers for the current shard.
Fixes #1598
> Fix 1598: Include allocations in responses from /add

- api/rest/client/client.go
- api/rest/client/lbclient.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/client/request.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- cluster.go
- cluster_test.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
- connect_graph.go
- go.mod
- go.sum
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- peer_manager_test.go
- pnet_test.go
- rpc_api.go
- rpc_policy.go
- sharness/t0025-ctl-status-report-commands.sh
- test/rpc_api_mock.go
This commit makes all the changes to make Peers() a streaming call.
While Peers is usually a non problematic call, for consistency, all calls
returning collections assembled through broadcast to cluster peers are now
streaming calls.
> Streaming Peers(): make Peers() a streaming call

- add_test.go
- adder/adder.go
- adder/adderutils/adderutils.go
- adder/ipfsadd/add.go
- adder/sharding/dag_service.go
- adder/sharding/dag_service_test.go
- adder/sharding/shard.go
- adder/single/dag_service.go
- adder/single/dag_service_test.go
- adder/util.go
- api/ipfsproxy/ipfsproxy.go
- cluster.go
- cluster_test.go
- ipfscluster.go
- ipfscluster_test.go
- ipfsconn/ipfshttp/ipfshttp.go
- ipfsconn/ipfshttp/ipfshttp_test.go
- rpc_api.go
- rpc_policy.go
- rpcutil/policygen/policygen.go
- test/ipfs_mock.go
- test/rpc_api_mock.go
This commit fixes #810 and adds block streaming to the final destinations when
adding. This should add major performance gains when adding data to clusters.
Before, everytime cluster issued a block, it was broadcasted individually to
all destinations (new libp2p stream), where it was block/put to IPFS (a single
block/put http roundtrip per block).
Now, blocks are streamed all the way from the adder module to the ipfs daemon,
by making every block as it arrives a single part in a multipart block/put
request.
Before, block-broadcast needed to wait for all destinations to finish in order
to process the next block. Now, buffers allow some destinations to be faster
than others while sending and receiving blocks.
Before, if a block put request failed to be broadcasted everywhere, an error
would …
> Adders: stream blocks to destinations

- adder/single/dag_service.go
- adder/util.go
- ipfsconn/ipfshttp/ipfshttp.go
- rpc_api.go
This PR contains a few small fixes related to adding blocks.
> Fixes to BlockStream and adder

- api/common/api.go
- api/common/test/helpers.go
- api/rest/client/request.go
This is to potentially address things like this:
https://github.com/nodejs/undici/issues/432#issuecomment-1047931107
> Always include the X-Stream-Error trailer (even without errors)

- api/types.go
The pin type in json objects will not be understandable by humans
> types: serialize pin types as string and not as a number

- ipfsconn/ipfshttp/ipfshttp.go
Because we are adding blocks on a single call, and we choose the format
parameter based on the prefix of the first block, IPFS will return block CIDs
based on that option.
This caused warnings when adding content that has multiple CID prefixes: for
example, any cid-version=1 file will include both dag-pb CIDs and raw
CIDs. Since the first block is usually a leave, IPFS will only return
raw-cids, and cause a warning because of the CID-mistmatch.
This fixes things by comparing multihashes only.
But! We might be writing blocks with the wrong CID and then the good CID won't
work!
Correct, we might, in some corner cases.
In go-ipfs >= 0.12.0, all blocks are addressed by multihash so CID prefixes
are irrelevant. This problem does not exist in that case.
In go-ipfs < 0.12.0, if a read for a …
> Fix warnings on block-cid mismatch when adding

- consensus/crdt/consensus.go
- consensus/raft/consensus.go
- consensus/raft/consensus_test.go
- consensus/raft/log_op_test.go
- monitor/metrics/checker.go
- observations/metrics.go
- pintracker/optracker/operation.go
- pintracker/optracker/operationtracker.go
- pintracker/pintracker_test.go
- pintracker/stateless/stateless_test.go
- state/dsstate/datastore.go
- state/dsstate/datastore_test.go
- test/ipfs_mock.go
This fixes #1470 and #1187.
This removes existing exported metrics (3 of which were not ever issued) and adds metrics for:
* Total number of pins
* Pins queued
* Pins pinning
* Pins in pin error
> metrics: track total pins, queued, pinning, pin error.

- consensus/crdt/consensus.go
- ipfsconn/ipfshttp/ipfshttp.go
When batching is enabled, the "batchingstate" is used to add/remove pins, but the
non-batching state is used as read-only state for doing List().
This means that both states will be writing pins metrics but the batching
state is never used for List(), so it never has the right total number.
This fixes that.
> Fix: wrong pins metric when batching enabled

- observations/metrics.go
- pintracker/optracker/operation.go
- pintracker/optracker/operation_test.go
- pintracker/optracker/operationtracker.go
We were currently tracking this metrics as a counter (SUM). The number is
good, but conceptually this is more a gauge (LastValue), given it can go down.
Thus we switch it by tracking the aggregation numbers directy in the operation
tracker.
> pintracker: metrics: convert pinning/queued/error metrics to gauges

- ipfsconn/ipfshttp/ipfshttp.go
Adding keeps retrying indefinitely to send blocks to ipfs. When ipfs is down this:
* Stores all errors
* Keeps retrying
* Additionally, forgot to close bodies
This resulted in memory leaks. The new behaviour does not keep retrying. And
response bodies are closed after reading.
> Fix: bad behaviour when adding and ipfs is down

- informer/disk/disk.go
Peers with 0 storage will not be allocated things.
> Do not issue freespace metric when free-space is 0.

- api/rest/client/lbclient.go
- cluster.go
I think this should fix the issue. As solution we make every retry with a
temporary channel and copy results to the final channel which is only closed
by us. This only affects streaming methods.
> Fix #1655: rest api lbclients panic on error with streaming methods

- cmd/ipfs-cluster-ctl/main.go
Seems we forgot to adapt "pin ls" and run it in a background goroutine, so it
just hangs.
> ctl: fix "pin ls" hangs for pinsets > 1024 items.

- adder/adder_test.go
- adder/util.go
- go.mod
- go.sum
- test/sharding.go
The issue happened because transparently upgrading to a HAMT directory attempted to read from our write-only ClusterDAGService. See #1691.
> Fix #1691: adding fails on large directories

- api/pinsvcapi/config.go
- api/pinsvcapi/pinsvc/pinsvc.go
- api/pinsvcapi/pinsvcapi.go
- api/pinsvcapi/pinsvcapi_test.go
These changes fix a few bugs in the PinSVC API and have been discovered by
running the compliance tool at https://github.com/ipfs-shipyard/pinning-service-compliance.
In particular, the error objects did not respect the spec, filters and counts
were not done right. An additional PR will follow with fixes to the pintracker
because some pin status information was not correctly set.
> PinSVC API: fix bugs and increase compliance

- pintracker/optracker/operationtracker.go
- pintracker/stateless/stateless.go
- pintracker/stateless/stateless_test.go
The operation tracker was not setting some fields correctly when producing
PinInfo objects. Additionally, recover operations were submitted with empty
pin objects, which resulted in the status for pins sent on recover operations
to be missing fields.
> pintracker: fix status objects missing or having wrong fields

- cmd/ipfs-cluster-ctl/formatters.go
> ctl: Expiration date in "pin ls" was showing wrong field (timestamp)

- api/common/config.go
Currently the debug messages are a bit confusing.
> api: improve tls setup debug logging

- pintracker/optracker/operation.go
- pintracker/optracker/operationtracker.go
By substracing 1 on every cancel we are double-counting.
> Fix: operationtracker metrics go negative

- ipfsconn/ipfshttp/ipfshttp.go
This fixes two bugs. First, the "blockPut response CID does not match the
multihash" warning was coming up when it shouldn't. Particularly, the
multipart reader called Node() several times for the same block, resulting in
CIDs been removed from the Seen set, and causing the warning when there were
several blocks (usually the empty dir block).
This also means we were counting Blockputs (and total data added) wrong in the
metrics, double-counting some blocks as these were recorded in Node() calls.
The fix makes the tracking in Next(), which is only called once for each
block. To avoid timing issues between Block reads from the channel and
blockput responses, the Seen set now stores how many times we have seen a
block. Thus a duplicated block that will get two BlockPut responses will not …
> ipfshttp: Fix "seen blocks" tracking and blockPut metrics

- api/ipfsproxy/headers.go
- api/ipfsproxy/ipfsproxy.go
- api/ipfsproxy/ipfsproxy_test.go
- test/ipfs_mock.go
The `dag/put` and `block/put` endpoints in Kubo provide the option of passing pin=true, upon which they create a recursive pin. It is fair to say that the ipfsproxy should in such cases make a cluster pin.
The implementation here is a bit more complex than in other routes because we need to proxy the request and at the same time we need to intercept the response and do the pinning. To make things more complex (specially for testing), request bodies can be multiparts carrying multiple blocks or dag objects.
One thing to note is that cluster will forward the block/put, dag/put queries with pin=false, since it will be cluster who instructs the right ipfs daemons to pin, which may be others and not the local one.
This fixes #1738.
> ipfsproxy: intercept block/put and dag/put and pin to cluster on pin=true

- api/common/api.go
- cluster.go
- cluster_test.go
- ipfscluster.go
- ipfsconn/ipfshttp/ipfshttp.go
- pintracker/stateless/stateless.go
This PR introduces a series of improvements in how the cluster peer deals with non-responding IPFS daemons:
* On boot, the cluster will wait for IPFS to be available
* The pintracker will return an error on StatusAll/RecoverAll calls if ipfs is down
* The API will return an error rather than NoContent when there are no elements to stream and there has been an error (bug)
* In case of 10 requests failures to IPFS, a rate limit of 1 req/s until a request suceeds is introduced.
This should improve the cluster peer behaviour during IPFS issues, which right now results in endless retrying and associated CPU/memory increases, which do not help IPFS recover or restart swiftly.
Fixes #1733.
> Behaviour improvements when the ipfs daemon is unavailable

- api/rest/client/request.go
- cluster.go
- consensus/raft/consensus.go
- ipfsconn/ipfshttp/ipfshttp.go
- pintracker/optracker/operation.go
- pintracker/optracker/operationtracker.go
We are propagating the wrong context (mostly from the Cluster top-level methods). This makes that request cancellations (and cancellations of the associated contexts) are not propagated to many methods, and can result in deadlocks when an operation that is holding a lock is not aborted.
This affects for example the operation tracker. Getting all operations from the tracker relies on someone reading from the out channel, or on the context being cancelled. When a request is aborted in the middle of the response, and the context is not cancelled, everything that wants to list operations would become deadlocked, including operations that need write locks like TrackNewOperation.
This fixes it.
> Fix bad context propagation / deadlocks

- cluster.go
- consensus/raft/consensus.go
- ipfscluster_test.go
- pintracker/stateless/stateless.go
Long story: Since #1768 there has been a recurring repinning test failure with
Raft consensus.
Per the test, if a pin is allocated to a peer that has been shutdown,
submitting the pin again should re-allocate it to a peer that is still
running.
Investigation on why this test fails and why it fails only in Raft lead to
realizing that this and other similar tests, were passing by chance. The
needed re-allocations were made not by the new submission of the pin, but by
the automatic-repinning feature. The actual resubmitted pin was carrying the
same allocations (one of them being the peer that was down), but it was
silently failing because the RedirectToLeader() code path was using
cc.ctx and hitting the peer that had been shutdown, which caused it to error.
Fixing the context propagation, …
> Fix: repinning does not re-allocate as needed

- Dockerfile
- Dockerfile-bundle
- Dockerfile-test
Git refuses to run `git rev-parse HEAD` now, in docker.
> Fix docker build failure (git safe directory)

- ipfsconn/ipfshttp/ipfshttp.go
Fixes: #1835.
If IPFS introduces a new multiaddress type/string that we have not compiled, we error. This caused issues with latest ipfs version (which we fixed by upgrading libraries too). This makes cluster a bit more future proof with upcoming ipfs versions.
> ipfsconn: do not error when we cannot parse multiaddresses from ipfs.

- clusterhost.go
Per https://github.com/libp2p/go-libp2p/issues/1852, the AutoRelay subsystem is now panicking on users. EnableAutoRelay must now be called with options, otherwise it seems to panic for some people.
Disabling it is the best for now, given relays are enabled and a node must be able to connect to others on bootstrap, perhaps it does not need to re-discover new relays (every other node should be a relay).
In any case we should revisit relay support and related services in Cluster, since semantics have changed a lot in libp2p, relayV2 is a thing, hole-punching is a thing etc. etc.
> Fix #1796: Disable AutoRelay

- Dockerfile
- Dockerfile-bundle
- Dockerfile-test
LevelDB was set for reasons that I don't remember. It might have been related to reduce the amount of space used by cluster. Pebble is most likely a better choice for Docker containers.
> Switch Dockerfiles to use Pebble datastore backend

- .github/workflows/tests.yml
- Dockerfile-bundle
- Dockerfile-test
- README.md
- docker-compose.yml
- sharness/lib/test-lib.sh
@hsanjuan we are still dual publishing under both names, but it is safer to use the new name.
> chore: switch to ipfs/kubo docker image

- cmd/ipfs-cluster-service/daemon.go
- go.mod
Uses the [sd_notify API](https://www.freedesktop.org/software/systemd/man/sd_notify.html) to send a readiness notification to systemd, suitable for `Type=notify` services.
Reuses the existing (previously indirect) dependency on `github.com/coreos/go-systemd`
> Send readiness notification to systemd

- allocate.go
- cluster_config.go
- cluster_config_test.go
Fixes #1976
This PR adds support for pinning only on untrusted peers. This feature is enabled via a new `pin_only_on_untrusted_peers` config setting (default `false`).
> This feature is the inverse of the existing `pin_only_on_trusted_peers`.
Configuring both `pin_only_on_trusted_peers` and `pin_only_on_untrusted_peers` to `true` results in a config validation error.
> Add support for configurable pinning only on untrusted peers

- cmd/ipfs-cluster-follow/commands.go
This PR enables the `numpin` and `pinqueue` metrics informers in `ipfs-cluster-follow`, identical to `ipfs-cluster-service`. This mitigates unintentional filtering of follower peers when allocating pins in collaborative networks.
Closes #2011
> Enable numpin and pinqueue informers in ipfs-cluster-follow

- ipfsconn/ipfshttp/ipfshttp.go
I cannot remember the reason this was done this way. It seems stupid now. Hopefully it was stupid.
> Fix #2004: Do not pre-resolve node_multiaddress

- datastore/pebble/config.go
- datastore/pebble/pebble.go
Additionally, add a warning when not using the newest version.
> pebble: Set default format_major_version to the newest

- datastore/pebble/config.go
- datastore/pebble/config_test.go
- logging.go
Do not overwrite the default max_concurrent_compactions unless the configuration value is > 0.
Fix debug and event logging coming from pebble.
> pebble: fix and improve debug logging / safe settings

- config/util.go
Empty defaults should become an empty array and not "null", even if a single string is understood as value for Unmarshaling.
> config: util.Strings with 0 length should json.Marshal as "[]"

- cmd/ipfs-cluster-ctl/graph.go
- go.mod
- go.sum
Kishan's go-dot has been deleted, but I kept the copy of the vendored code. So I have forked original's ZenGround0/go-dot and added kishans contribution as a single commit on top and we'll use that for the time being.
Fixes #2052 .
> deps: replace kishansagathiya/go-dot with ipfs-cluster/go-dot

- cluster.go
- cluster_config.go
- clusterhost.go
- cmd/ipfs-cluster-follow/commands.go
- internal/fd/fd.go
- internal/fd/sys_not_unix.go
- internal/fd/sys_unix.go
- pstoremgr/pstoremgr.go
To address the issues in #2039 this adds control of the libp2p resource managers and improves the "reBootstrap" logic so that peers do not continuously reconnect to the 3 most-prioritary peers in the cluster.
> Fix #2039: resource manager and re-connection improvements

- api/rest/client/client.go
- api/rest/client/lbclient.go
- api/rest/client/methods.go
- api/rest/client/methods_test.go
- api/rest/restapi.go
- api/rest/restapi_test.go
- api/types.go
- cluster.go
- cluster_test.go
- clusterhost.go
- cmd/ipfs-cluster-ctl/formatters.go
- cmd/ipfs-cluster-ctl/main.go
- cmd/ipfs-cluster-follow/commands.go
- cmd/ipfs-cluster-service/daemon.go
- go.mod
- ipfscluster_test.go
- observations/config.go
- observations/setup.go
- rpc_api.go
- rpc_policy.go
- test/rpc_api_mock.go
This has two parts:
- First, wire in libp2p metrics into the prometheus endpoint. They do not include per-protocol bandwidth metrics but it should have been nevertheless exposed and it was an oversight that it wasn't there.
- Second: add a health/bandwidth endpoint that reports bandwidth stats as given by GetBandwidthByProtocol(). Contains server/client and tests.
`ipfs-cluster-ctl health bandwidth` can be used to display the stats in a prettified way.
> Expose libp2p metrics and bandwidth stats for libp2p protocols

- ipfsconn/ipfshttp/config.go
- ipfsconn/ipfshttp/ipfshttp.go
- monitor/pubsubmon/pubsubmon.go
Mainly update informer metrics both at the start and at the end of the pinning operation (always subject to trigger_interval).
Fix some typos.
> ipfshttp: improve logic to update informer metrics

- cluster_config.go
- clusterhost.go
- config_test.go
- ipfscluster_test.go
- peer_manager_test.go
See diff. This is an attempt to:
1) Reduce pubsub chatter
2) Reduce pubsub bandwidth
3) Tolerate slower peers better
Rationale: less hearbeats, more leeways, larger mesh for less replays and faster distribution.
> gossipsub: optimize for diverse clusters with many peers

- datastore/pebble/pebble.go
- go.mod
- go.sum
@hsanjuan  fyi this PR updates `go-ds-pebble` to version with updated constructor from https://github.com/ipfs/go-ds-pebble/pull/39 by  @gammazero
> chore: update to go-ds-pebble v0.4.0

- ipfsconn/ipfshttp/ipfshttp.go
The number of pins in ipfs should be recorded when NO error happens, and not the otherway around.
> ipfshttp: fix recording total ipfs pins

- cmd/ipfs-cluster-follow/commands.go
- cmd/ipfs-cluster-service/daemon.go
I fixed the error message during the initialization of the tags informer in ipfs-cluster-service and ipfs-cluster-follow because it was the error message for the numpin informer.
> Fix the error message during the initialization of tags informer

- docker/get-docker-tags.sh
The latest tag should be set to the latest release, or at least that is how we used to roll before moving to github-docker-builds.
Fixes #2133.
> docker: tag "latest" when releasing

- ipfsconn/ipfshttp/ipfshttp.go
Fix nil pointer panic when using a separate swarm protocol.
```
2025-03-31T03:31:19.035Z        WARN    ipfshttp        ipfshttp/ipfshttp.go:376        cannot parse IPFS multiaddress: /ip4/127.0.0.1/udp/4003/kcp+scop/p2p/12D3Koo... (%!w(*errors.errorString=&{failed to parse multiaddr "/ip4/127.0.0.1/udp/4003/kcp+scop/p2p/12D3Koo...": unknown protocol kcp+scop}))... ignoring
2025-03-31T03:31:19.036Z        INFO    cluster ipfs-cluster/cluster.go:813     IPFS is ready. Peer ID: 12D3Koo...
2025-03-31T03:31:19.036Z        INFO    cluster ipfs-cluster/cluster.go:821     ** IPFS Cluster is READY **
2025-03-31T03:31:19.037Z        WARN    ipfshttp        ipfshttp/ipfshttp.go:376        cannot parse IPFS multiaddress: /ip4/127.0.0.1/udp/4003/kcp+scop/p2p/12D3Koo... …
```
> Fix add nil for unknown multiaddr
